### ISSUE TITLE
Weapon Station crash bug

### ISSUE THREAD

**Issue by gp009** [simeonradivoev/MatterOverdrive#142]
this crash results loss of items involved in the UI of the weapon station

Forge 10.13.4.1492.1.7.10

MatterOverdrive 1.7.10-0.4.0-RC2

Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at matteroverdrive.util.MOInventoryHelper.setInventorySlotContents(MOInventoryHelper.java:21)
	at matteroverdrive.data.ItemInventoryWrapper.func_70299_a(ItemInventoryWrapper.java:49)
	at matteroverdrive.tile.TileEntityWeaponStation.func_70299_a(TileEntityWeaponStation.java:149)
	at net.minecraft.inventory.Slot.func_75215_d(Slot.java:77)
	at net.minecraft.inventory.Container.func_75131_a(SourceFile:390)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147241_a(NetHandlerPlayClient.java:1062)
	at net.minecraft.network.play.server.S30PacketWindowItems.func_148833_a(SourceFile:49)
	at net.minecraft.network.play.server.S30PacketWindowItems.func_148833_a(SourceFile:11)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1602)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at matteroverdrive.util.MOInventoryHelper.setInventorySlotContents(MOInventoryHelper.java:21)
	at matteroverdrive.data.ItemInventoryWrapper.func_70299_a(ItemInventoryWrapper.java:49)
	at matteroverdrive.tile.TileEntityWeaponStation.func_70299_a(TileEntityWeaponStation.java:149)
	at net.minecraft.inventory.Slot.func_75215_d(Slot.java:77)
	at net.minecraft.inventory.Container.func_75131_a(SourceFile:390)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147241_a(NetHandlerPlayClient.java:1062)
	at net.minecraft.network.play.server.S30PacketWindowItems.func_148833_a(SourceFile:49)
	at net.minecraft.network.play.server.S30PacketWindowItems.func_148833_a(SourceFile:11)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)

**Comment by simeonradivoev** [comment]
when does that crash occur ?

**Comment by gp009** [comment]
when it crashed first time when I click on an item in inventory in the weapon station GUI
items in the GUI weapon upgrade slots are lost

when reloading world after the first crash it crashes again after clicking on the weapon station block itself
