### ISSUE TITLE
NullPointerException while trying to scan obsidian in the Matter Analyzer

### ISSUE THREAD

**Issue by Modbder** [simeonradivoev/MatterOverdrive#169]
Hello. I was playing with the mod in my survival world. Everything was working properly, until I decided to teach my Matter Network an Obsidian block. It scanned the obsidian up to 80% just fine, but upon scanning it to a 100 it crashed my game. It is worth noticing that my system consists of 8 pattern storages, and they are full with pattern drives. I already had 17 items successfully scanned and stored in the drives, and they work completely fine.

I'm using forge 10.13.4.1448
I'm using java 1.8.0_51
I'm using MatterOverdrive 0.4.0-RC2

I can join my world just fine, but ~10 seconds later I crash with the same error. I suspect it is because the Matter Analyzer is finding the pattern storage that tick.
I had to quickly break the Analyzer to stop the world from crashing, since for some reason I could not remove the Search For Pattern Storage task from the analyzer's GUI.

Crash report:

java.lang.NullPointerException
at matteroverdrive.tile.TileEntityMachinePatternStorage.addItem(TileEntityMachinePatternStorage.java:210) ~[TileEntityMachinePatternStorage.class:?]

at matteroverdrive.tile.TileEntityMachinePatternStorage.canPreform(TileEntityMachinePatternStorage.java:330) ~[TileEntityMachinePatternStorage.class:?]

at matteroverdrive.util.MatterNetworkHelper.broadcastTaskInDirection(MatterNetworkHelper.java:41) ~[MatterNetworkHelper.class:?]

at matteroverdrive.tile.pipes.TileEntityNetworkPipe.broadcast(TileEntityNetworkPipe.java:97) ~[TileEntityNetworkPipe.class:?]

at matteroverdrive.util.MatterNetworkHelper.broadcastTaskInDirection(MatterNetworkHelper.java:35) ~[MatterNetworkHelper.class:?]

at matteroverdrive.tile.TileEntitiyMachinePacketQueue.handlePacketBroadcast(TileEntitiyMachinePacketQueue.java:171) ~[TileEntitiyMachinePacketQueue.class:?]

at matteroverdrive.tile.TileEntitiyMachinePacketQueue.onNetworkTick(TileEntitiyMachinePacketQueue.java:136) ~[TileEntitiyMachinePacketQueue.class:?]

at matteroverdrive.handler.MatterNetworkTickHandler.onWorldTick(MatterNetworkTickHandler.java:26) ~[MatterNetworkTickHandler.class:?]

at matteroverdrive.handler.TickHandler.onWorldTick(TickHandler.java:82) ~[TickHandler.class:?]

at cpw.mods.fml.common.eventhandler.ASMEventHandler_103_TickHandler_onWorldTick_WorldTickEvent.invoke(.dynamic) ~[?:?]

at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]

at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:?]

at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:255) [FMLCommonHandler.class:?]

at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:645) [MinecraftServer.class:?]

at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]

at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) [bsx.class:?]

at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]

Here is the full fml-client-latest.log in case you need it:
http://pastebin.com/0uJjwzMv

**Comment by simeonradivoev** [comment]
Fixed in 85f24538b09a0383190b26191570640cd20707c6

**Comment by handicraftsman** [comment]
))
