### ISSUE TITLE
Upgraded from RC2 to RC3 and server now crashes on start

### ISSUE THREAD

**Issue by Nimmo** [simeonradivoev/MatterOverdrive#173]
I updated from 0.4.0 RC2 to 0.4.0 RC3 and the server now crashes on startup.

Here is the crash log that is generated by forge:
http://pastebin.ca/3116340

Everything was running perfectly well before the server was stopped, the mod updated and the server restarted.
Let me know if there's any additional information needed.

**Comment by simeonradivoev** [comment]
Can you send me the whole log ?

**Comment by Nimmo** [comment]
Ah, my apologies, here it is:
http://pastebin.ca/3116366

**Comment by Nimmo** [comment]
Here is a non clipped version: https://www.dropbox.com/s/j3egqr1qwyscwns/fml-server-latest.log?dl=0

**Comment by simeonradivoev** [comment]
i don't think that's the one. Try and run the server. When you crash then copy the fml-server-latest.log withour running the server again.

**Comment by Nimmo** [comment]
I've got it now. Sorry for the delay, but here it is now:

http://pastebin.ca/3116837

**Comment by Nimmo** [comment]
For what it's worth I've now gone in on an old backup of the world and I see that a lot of my blocks from mods have been switched around quite a bit, many either missing or replaced with different items, so I'm wondering if something has corrupted the world. After removing all of these odd blocks I've restarted the server with the new RC3 version and it seems to be starting ok.

This won't have solved the problem, but I guess I've sidestepped it.

**Comment by Kazzamkablam** [comment]
Can confirm, same thing happening with my old world with following crash report when loading it:

Description: Exception in server tick loop

java.lang.ArrayIndexOutOfBoundsException: 7
	at extrabiomes.items.ItemNewSapling.func_77667_c(ItemNewSapling.java:33)
	at net.minecraft.item.ItemStack.func_77977_a(ItemStack.java:361)
	at matteroverdrive.handler.MatterRegistry.getEntry(MatterRegistry.java:304)
	at matteroverdrive.util.MatterHelper.getMatterAmountFromItem(MatterHelper.java:66)
	at matteroverdrive.handler.thread.RegisterItemsFromRecipes.registerFromFurnace(RegisterItemsFromRecipes.java:179)
	at matteroverdrive.handler.thread.RegisterItemsFromRecipes.run(RegisterItemsFromRecipes.java:120)
	at java.lang.Thread.run(Unknown Source)
	at matteroverdrive.MatterOverdrive.serverStart(MatterOverdrive.java:164)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.serverStarted(Loader.java:802)
	at cpw.mods.fml.common.FMLCommonHandler.handleServerStarted(FMLCommonHandler.java:283)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:389)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by simeonradivoev** [comment]
@Kazzamkablam You crash is for a completely different reason. And Matter overdrive is not entirely to blame. Extrabiomes caused the crash.

**Comment by shadowfacts** [comment]
Closed due to inactivity.
