### ISSUE TITLE
Issue with newest version of Matter Overdrive and Extrabiomes

### ISSUE THREAD

**Issue by Kazzamkablam** [simeonradivoev/MatterOverdrive#176]
Posting on a separate thread as requested

Description: Exception in server tick loop

java.lang.ArrayIndexOutOfBoundsException: 7
at extrabiomes.items.ItemNewSapling.func_77667_c(ItemNewSapling.java:33)
at net.minecraft.item.ItemStack.func_77977_a(ItemStack.java:361)
at matteroverdrive.handler.MatterRegistry.getEntry(MatterRegistry.java:304)
at matteroverdrive.util.MatterHelper.getMatterAmountFromItem(MatterHelper.java:66)
at matteroverdrive.handler.thread.RegisterItemsFromRecipes.registerFromFurnace(RegisterItemsFromRecipes.java:179)
at matteroverdrive.handler.thread.RegisterItemsFromRecipes.run(RegisterItemsFromRecipes.java:120)
at java.lang.Thread.run(Unknown Source)
at matteroverdrive.MatterOverdrive.serverStart(MatterOverdrive.java:164)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
at com.google.common.eventbus.EventBus.post(EventBus.java:275)
at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
at com.google.common.eventbus.EventBus.post(EventBus.java:275)
at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
at cpw.mods.fml.common.Loader.serverStarted(Loader.java:802)
at cpw.mods.fml.common.FMLCommonHandler.handleServerStarted(FMLCommonHandler.java:283)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:389)
at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by simeonradivoev** [comment]
Fixed in f2d7b292d02f06d59a9521812e5adcd5c504050c
