### ISSUE TITLE
 java.lang.ArrayIndexOutOfBoundsException: 16

### ISSUE THREAD

**Issue by Horneat** [simeonradivoev/MatterOverdrive#185]
java.lang.ArrayIndexOutOfBoundsException: 16
	at Reika.RotaryCraft.Base.ItemMulti.func_77667_c(ItemMulti.java:329)
	at net.minecraft.item.ItemStack.func_77977_a(ItemStack.java:361)
	at matteroverdrive.handler.thread.RegisterItemsFromRecipes.run(RegisterItemsFromRecipes.java:96)
	at java.lang.Thread.run(Thread.java:745)
	at matteroverdrive.MatterOverdrive.serverStart(MatterOverdrive.java:170)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.serverStarted(Loader.java:802)
	at cpw.mods.fml.common.FMLCommonHandler.handleServerStarted(FMLCommonHandler.java:283)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:389)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by Horneat** [comment]
The Game Crash when i load or generate a new World

**Comment by simeonradivoev** [comment]
You blacklist RotaryCraft for Matter Recipe Calculation

**Comment by Horneat** [comment]
what

**Comment by simeonradivoev** [comment]
In the config file for MatterOverdrive blacklist RotaryCraft. RotaryCraft is causing the crash.

**Comment by Horneat** [comment]
oh ok i try

**Comment by Horneat** [comment]
it take so long to start the game with 212 mods .

**Comment by Horneat** [comment]
how to black list the mod

**Comment by simeonradivoev** [comment]
```Java
S:mod_blacklist <
     RotaryCraft
>
```

**Comment by MrGraphic** [comment]
So I come here from #181 ...
@simeonradivoev it seems that blacklist doesn't work as intendent in this case.
Btw, where is now registry file ?

**Comment by simeonradivoev** [comment]
It's in the same place as before. It's just renamed as Registry.matter

**Comment by MrGraphic** [comment]
Oh right, I was unable to find that file because there was non due that issue with rotarycraft.

**Comment by Horneat** [comment]
waite a min

**Comment by Horneat** [comment]
must i turn automatic matter calculation from recipe false

**Comment by Horneat** [comment]
to

**Comment by simeonradivoev** [comment]
if it doesn't work yes

**Comment by Horneat** [comment]
wait

**Comment by MrGraphic** [comment]
@simeonradivoev blacklist doesn't work at all. Just added few modIDs and I still see matter cost for items that has been auto calculated from recipes. Of course I deleted registry.

**Comment by Horneat** [comment]
jes it don`t work

**Comment by Horneat** [comment]
how i find the mod iD out

**Comment by Horneat** [comment]
is it the name of the mod File

**Comment by Horneat** [comment]
ok with the blacklist it dont work

**Comment by Horneat** [comment]
i have a question for what is the Sights Slot for the Phaser Rifle
