### ISSUE TITLE
Crash with MalisisDoors

### ISSUE THREAD

**Issue by DeadLord** [simeonradivoev/MatterOverdrive#188]
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 23.08.15 2:05
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at net.malisis.doors.block.VanishingBlock.func_149749_a(VanishingBlock.java:220)
	at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:600)
	at net.minecraft.world.World.func_147465_d(World.java:451)
	at matteroverdrive.tile.TileEntityGravitationalAnomaly.brakeBlock(TileEntityGravitationalAnomaly.java:549)
	at matteroverdrive.tile.TileEntityGravitationalAnomaly.manageBlockDestory(TileEntityGravitationalAnomaly.java:429)
	at matteroverdrive.tile.TileEntityGravitationalAnomaly.onServerTick(TileEntityGravitationalAnomaly.java:295)
	at matteroverdrive.handler.TickHandler.onWorldTick(TickHandler.java:99)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_259_TickHandler_onWorldTick_WorldTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:255)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:645)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by simeonradivoev** [comment]
You should also post the crash to MalisisDoors

**Comment by DeadLord** [comment]
ok
