### ISSUE TITLE
ClassNotFoundException:matteroverdrive.MatterOverdrive

### ISSUE THREAD

**Issue by theProphet666** [simeonradivoev/MatterOverdrive#191]
Attempting to make a ModPack with Matter Overdrive. All the other mods work fine with each other, as soon as I enter Matter Overdrive to the occasion I get this. Doesn't seem to be ID Conflict or Recipe issues. Soooo... any help?

```
cpw.mods.fml.common.LoaderException: java.lang.ClassNotFoundException: matteroverdrive.MatterOverdrive
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:544)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:208)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)
Caused by: java.lang.ClassNotFoundException: matteroverdrive.MatterOverdrive
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at cpw.mods.fml.common.ModClassLoader.loadClass(ModClassLoader.java:58)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:440)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:513)
	... 18 more
Caused by: java.lang.UnsupportedClassVersionError: matteroverdrive/MatterOverdrive : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 45 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.7.0_79, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1477762384 bytes (1409 MB) / 1794113536 bytes (1711 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx4096m -XX:PermSize=256m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 116 mods loaded, 116 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UC	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UC	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1448-1.7.10-universal.jar) 
	UC	Forge{10.13.4.1448} [Minecraft Forge] (forge-1.7.10-10.13.4.1448-1.7.10-universal.jar) 
	UC	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UC	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UC	NotEnoughItems{1.0.5.111} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.111-universal.jar) 
	UC	OpenComputers|Core{1.5.15.31} [OpenComputers (Core)] (minecraft.jar) 
	UC	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UC	FusionWarfare{1.7.10-1.1.0} [Fusion Warfare] ((NEW) FusionWarfare-1.7.10-1.1.0.jar) 
	UC	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UC	Artifacts{1.1.3} [Artifacts] (Artifacts-1.1.3.jar) 
	UC	CoFHCore{1.7.10R3.0.3} [CoFH Core] (CoFHCore-[1.7.10]3.0.3-303.jar) 
	UC	BuildCraft|Core{7.0.21} [BuildCraft] (buildcraft-7.0.21.jar) 
	UC	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) 
	UC	Natura{2.2.0} [Natura] (natura-1.7.10-2.2.0.1.jar) 
	UC	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1387-universal.jar) 
	UC	ExtrabiomesXL{3.16.2} [ExtrabiomesXL] (extrabiomesxl_1.7.10-3.16.2.jar) 
	UC	IC2{2.2.765-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.765-experimental.jar) 
	UC	Forestry{3.6.3.20} [Forestry for Minecraft] (forestry_1.7.10-3.6.3.20.jar) 
	UC	MineFactoryReloaded{1.7.10R2.8.0} [MineFactory Reloaded] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UC	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) 
	UC	Artifice{1.7.10R1.1.4} [Artifice] (Artifice-1.7.10-1.1.5R-399.jar) 
	UC	bdlib{1.9.0.94} [BD Lib] (bdlib-1.9.0.94-mc1.7.10.jar) 
	UC	BiblioCraft{1.10.5} [BiblioCraft] (BiblioCraft[v1.10.6][MC1.7.10].jar) 
	UC	BiblioWoodsBoP{1.9} [BiblioWoods Biomes O'Plenty Edition] (BiblioWoods[BiomesOPlenty][v1.9].jar) 
	UC	BiblioWoodsEBXL{1.4} [BiblioWoods ExtraBiomesXL Edition] (BiblioWoods[ExtraBiomesXL][v1.4].jar) 
	UC	BiblioWoodsForestry{1.7} [BiblioWoods Forestry Edition] (BiblioWoods[Forestry][v1.7].jar) 
	UC	BiblioWoodsNatura{1.5} [BiblioWoods Natura Edition] (BiblioWoods[Natura][v1.5].jar) 
	UC	AWWayofTime{v1.3.3} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.7.10-1.3.3-13.jar) 
	UC	Botania{r1.7-212} [Botania] (Botania r1.7-212.jar) 
	UC	BuildCraft|Silicon{7.0.21} [BC Silicon] (buildcraft-7.0.21.jar) 
	UC	BuildCraft|Factory{7.0.21} [BC Factory] (buildcraft-7.0.21.jar) 
	UC	BuildCraft|Builders{7.0.21} [BC Builders] (buildcraft-7.0.21.jar) 
	UC	BuildCraft|Energy{7.0.21} [BC Energy] (buildcraft-7.0.21.jar) 
	UC	BuildCraft|Robotics{7.0.21} [BC Robotics] (buildcraft-7.0.21.jar) 
	UC	BuildCraft|Transport{7.0.21} [BC Transport] (buildcraft-7.0.21.jar) 
	UC	ChickenChunks{1.3.4.19} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.19-universal.jar) 
	UC	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UC	chisel{2.5.0.43} [Chisel 2] (Chisel2-2.5.0.43.jar) 
	UC	ChiselFacades{1.7.10-2.11-cricket} [Chisel Facades] (ChiselFacades-1.7.10-2.11-cricket.jar) 
	UC	ComputerCraft{1.74} [ComputerCraft] (ComputerCraft1.74.jar) 
	UC	divblocks{1.1} [DivBlocks] (DivBlocks-1.7.10-1.1.jar) 
	UC	GalacticraftCore{3.0.12} [Galacticraft Core] (GalacticraftCore-1.7-3.0.12.357.jar) 
	UC	GalacticraftMars{3.0.12} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.12.357.jar) 
	UC	gendustry{1.5.2.107} [GenDustry] (gendustry-1.5.2.107-mc1.7.10.jar) 
	UC	jcanimation{1.2.4} [JCAnimationAPI] (JurassiCraft-1.4.5.jar) 
	UC	llibrary{0.3.2-1.7.10} [LLibrary] (LLibrary-0.3.2-1.7.10.jar) 
	UC	jurassicraft{1.4.5} [JurassiCraft] (JurassiCraft-1.4.5.jar) 
	UC	ThermalFoundation{1.7.10R1.2.0} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.0-102.jar) 
	UC	ThermalExpansion{1.7.10R4.0.3B1} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.3B1-218.jar) 
	UE	mo{0.4.0-RC3} [Matter Overdrive] (MatterOverdrive-1.7.10-0.4.0-RC3.jar) 
	UC	RadixCore{2.0.2} [RadixCore] (RadixCore-1.7.10-2.0.2-universal.jar) 
	UC	MCA{1.7.10-5.0.7.2} [Minecraft Comes Alive] (MCA-1.7.10-5.0.7.2-universal.jar) 
	UC	MetallurgyCore{4.0.4} [Metallurgy Core] (MetallurgyCore-1.7.10-4.0.4.18.jar) 
	UC	Mekanism{8.1.7} [Mekanism] (Mekanism-1.7.10-8.1.7.252.jar) 
	UC	MekanismGenerators{8.1.7} [MekanismGenerators] (MekanismGenerators-1.7.10-8.1.7.252.jar) 
	UC	MekanismTools{8.1.7} [MekanismTools] (MekanismTools-1.7.10-8.1.7.252.jar) 
	UC	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UC	TConstruct{1.7.10-1.8.7.build979} [Tinkers' Construct] (TConstruct-1.7.10-1.8.7.jar) 
	UC	Metallurgy{4.0.6} [Metallurgy 4] (Metallurgy-1.7.10-4.0.6.80.jar) 
	UC	MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0} [MFR Compat: Applied Energistics] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UC	MineFactoryReloaded|CompatAtum{1.7.10R2.8.0} [MFR Compat: Atum] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UC	MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0} [MFR Compat: BackTools] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UC	MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0} [MFR Compat: BuildCraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UC	MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0} [MFR Compat: Chococraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UC	MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UC	MineFactoryReloaded|CompatForestry{1.7.10R2.8.0} [MFR Compat: Forestry] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UC	MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0} [MFR Compat: ForgeMicroblock] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UC	MineFactoryReloaded|CompatIC2{1.7.10R2.8.0} [MFR Compat: IC2] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UC	MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0} [MFR Compat: Mystcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UC	MrTJPCoreMod{1.1.0.31} [MrTJPCore] (MrTJPCore-1.1.0.31-universal.jar) 
	UC	ProjRed|Core{4.7.0pre8.92} [ProjectRed Core] (ProjectRed-1.7.10-4.7.0pre8.92-Base.jar) 
	UC	MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0} [MFR Compat ProjectRed] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UC	MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0} [MFR Compat: Railcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UC	MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UC	MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0} [MFR Compat: Thaumcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UC	MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0} [MFR Compat: Thermal Expansion] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UC	MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.0} [MFR Compat: Tinkers' Construct] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UC	MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0} [MFR Compat: TwilightForest] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UC	MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UC	MorePlanet{1.2.9} [More Planets] (More-Planets-1.7.10-1.2.9.jar) 
	UC	morechisels{@VERSION@} [More Chisels] (MoreChisels-1.7.10-1.0-20.jar) 
	UC	NEIAddons{1.12.11.36} [NEI Addons] (neiaddons-1.12.11.36-mc1.7.10.jar) 
	UC	NEIAddons|Developer{1.12.11.36} [NEI Addons: Developer Tools] (neiaddons-1.12.11.36-mc1.7.10.jar) 
	UC	NEIAddons|AppEng{1.12.11.36} [NEI Addons: Applied Energistics 2] (neiaddons-1.12.11.36-mc1.7.10.jar) 
	UC	NEIAddons|Botany{1.12.11.36} [NEI Addons: Botany] (neiaddons-1.12.11.36-mc1.7.10.jar) 
	UC	NEIAddons|Forestry{1.12.11.36} [NEI Addons: Forestry] (neiaddons-1.12.11.36-mc1.7.10.jar) 
	UC	NEIAddons|CraftingTables{1.12.11.36} [NEI Addons: Crafting Tables] (neiaddons-1.12.11.36-mc1.7.10.jar) 
	UC	NEIAddons|ExNihilo{1.12.11.36} [NEI Addons: Ex Nihilo] (neiaddons-1.12.11.36-mc1.7.10.jar) 
	UC	NetherOres{1.7.10R2.3.0} [Nether Ores] (NetherOres-[1.7.10]2.3.0-12.jar) 
	UC	ProjRed|Transmission{4.7.0pre8.92} [ProjectRed Transmission] (ProjectRed-1.7.10-4.7.0pre8.92-Integration.jar) 
	UC	OpenComputers{1.5.15.31} [OpenComputers] (OpenComputers-MC1.7.10-1.5.15.31-universal.jar) 
	UC	getalltheseeds{1.7.10a} [Pam's Get all the Seeds!] (Pam's Get all the Seeds 1.7.10a.jar) 
	UC	harvestcraft{1.7.10j} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10j.jar) 
	UC	ProjRed|Transportation{4.7.0pre8.92} [ProjectRed Transportation] (ProjectRed-1.7.10-4.7.0pre8.92-Mechanical.jar) 
	UC	ProjRed|Compatibility{4.7.0pre8.92} [ProjectRed Compatibility] (ProjectRed-1.7.10-4.7.0pre8.92-Compat.jar) 
	UC	ProjRed|Integration{4.7.0pre8.92} [ProjectRed Integration] (ProjectRed-1.7.10-4.7.0pre8.92-Integration.jar) 
	UC	ProjRed|Fabrication{4.7.0pre8.92} [ProjectRed Fabrication] (ProjectRed-1.7.10-4.7.0pre8.92-Fabrication.jar) 
	UC	ProjRed|Illumination{4.7.0pre8.92} [ProjectRed Illumination] (ProjectRed-1.7.10-4.7.0pre8.92-Lighting.jar) 
	UC	ProjRed|Expansion{4.7.0pre8.92} [ProjectRed Expansion] (ProjectRed-1.7.10-4.7.0pre8.92-Mechanical.jar) 
	UC	RedstoneArsenal{1.7.10R1.1.1} [Redstone Arsenal] (RedstoneArsenal-[1.7.10]1.1.1-89.jar) 
	UC	AS_Ruins{15.1} [Ruins Spawning System] (Ruins-1.7.10.jar) 
	UC	shipwrecks{1.7.0} [Shipwrecks!] (shipwrecks-1.7.10-1.7.1.jar) 
	UC	thaumcraftneiplugin{@VERSION@} [Thaumcraft NEI Plugin] (thaumcraftneiplugin-1.7.10-1.7a.jar) 
	UC	ThermalDynamics{1.7.10R1.1.0} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.1.0-161.jar) 
	UC	TMechworks{0.2.14.100} [Tinkers' Mechworks] (TMechworks-1.7.10-0.2.14.100.jar) 
	UC	WR-CBE|Core{1.4.1.9} [WR-CBE Core] (WR-CBE-1.7.10-1.4.1.9-universal.jar) 
	UC	WR-CBE|Addons{1.4.1.9} [WR-CBE Addons] (WR-CBE-1.7.10-1.4.1.9-universal.jar) 
	UC	WR-CBE|Logic{1.4.1.9} [WR-CBE Logic] (WR-CBE-1.7.10-1.4.1.9-universal.jar) 
	UC	harvestthenether{1.7.10} [Pam's Harvest the Nether] (ZZZPam's Harvest the Nether 1.7.10a.jar) 
	UC	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UC	ForgeRelocation{0.0.1.4} [ForgeRelocation] (ForgeRelocation-0.0.1.4-universal.jar) 
	UC	MCFrames{1.0} [MCFrames] (ForgeRelocation-0.0.1.4-universal.jar) 
	UC	RelocationFMP{0.0.1.2} [RelocationFMP] (ForgeRelocationFMP-0.0.1.2-universal.jar) 
	UC	aobd{2.8.1} [Another One Bites The Dust] (AOBD-2.8.1.jar) 
	UC	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.3.12618 Compatibility Profile Context 13.251.9001.1001' Renderer: 'AMD Radeon HD 7800 Series'
	CoFHCore: -[1.7.10]3.0.3-303
	Mantle Environment: Environment healthy.
	MineFactoryReloaded: -[1.7.10]2.8.0-104
	ThermalFoundation: -[1.7.10]1.2.0-102
	ThermalExpansion: -[1.7.10]4.0.3B1-218
	TConstruct Environment: Environment healthy.
	NetherOres: -[1.7.10]2.3.0-12
	RedstoneArsenal: -[1.7.10]1.1.1-89
	ThermalDynamics: -[1.7.10]1.1.0-161
```

Edit (shadowfacts): Formatting

**Comment by shadowfacts** [comment]
Use Java 8.

**Comment by simeonradivoev** [comment]
Java 8
