### ISSUE TITLE
Client crash when viewing locked skills in android station.

### ISSUE THREAD

**Issue by daeo** [simeonradivoev/MatterOverdrive#212]
In Version 1.7.10-0.4.0-RC2 , included with Horizons 2: Daybreaker

Getting crash when trying to view some locked android skills:

Description: Rendering screen 
 
java.lang.ArrayIndexOutOfBoundsException: -97 
at org.lwjgl.input.Keyboard.getKeyName(Keyboard.java:429) 
at matteroverdrive.data.biostats.BioticStatTeleport.getDetails(BioticStatTeleport.java:58) 
at matteroverdrive.data.biostats.AbstractBioticStat.onTooltip(AbstractBioticStat.java:180) 
at matteroverdrive.gui.element.ElementBioStat.addTooltip(ElementBioStat.java:81) 
at matteroverdrive.gui.element.ElementBaseGroup.handleTooltips(ElementBaseGroup.java:77) 
at matteroverdrive.gui.element.ElementBaseGroup.drawBackground(ElementBaseGroup.java:54) 
at cofh.lib.gui.GuiBase.drawElements(GuiBase.java:302) 
at matteroverdrive.gui.MOGuiBase.func_146976_a(MOGuiBase.java:75) 
at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:78) 
at cofh.lib.gui.GuiBase.func_73863_a(GuiBase.java:86) 
at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061) 
at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001) 
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) 
at net.minecraft.client.main.Main.main(SourceFile:148) 
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) 
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) 
at java.lang.reflect.Method.invoke(Unknown Source) 
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) 
at net.minecraft.launchwrapper.Launch.main(Launch.java:28) 

Crash affects client only.

**Comment by simeonradivoev** [comment]
that's because you have the mouse assigned as a key to the use ability. This is fixed in d6f57a30c041bfe075e6253fbe50daf63f014236
