### ISSUE TITLE
Matter Analyser crashes server

### ISSUE THREAD

**Issue by caeldom** [simeonradivoev/MatterOverdrive#218]
Minecraft 1.7.10
Matter Overdrive 0.3.4.1

Matter Analyser caused the server to crash when putting obsidian into it. Only 3 users online at the time. When the user logged back into the server, it crashed again. When I attempted to enter the chunk to remove the Matter Analyser, it also crashed the server.

```
---- Minecraft Crash Report ----
// Oops.

Time: 9/16/15 7:11 AM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at com.MO.MatterOverdrive.tile.TileEntityMachinePatternStorage.addItem(TileEntityMachinePatternStorage.java:207)
	at com.MO.MatterOverdrive.tile.TileEntityMachineMatterAnalyzer.analyzeItem(TileEntityMachineMatterAnalyzer.java:195)
	at com.MO.MatterOverdrive.tile.TileEntityMachineMatterAnalyzer.manageAnalyze(TileEntityMachineMatterAnalyzer.java:106)
	at com.MO.MatterOverdrive.tile.TileEntityMachineMatterAnalyzer.func_145845_h(TileEntityMachineMatterAnalyzer.java:75)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

Link to the full crash log http://pastebin.com/4raANCr3

**Comment by simeonradivoev** [comment]
It was fixed in 85f24538b09a0383190b26191570640cd20707c6. I think it's in the 0.4 RC3 Hotfix 3

**Comment by caeldom** [comment]
Ah so my server just hasn't updated?

**Comment by simeonradivoev** [comment]
Yes it seems so.
