### ISSUE TITLE
Getting fatal error disconnect in SMP

### ISSUE THREAD

**Issue by Saereth** [simeonradivoev/MatterOverdrive#260]
we are running the nuts and bolts pack on technic/ftb (code NutsandBolts). Forge 1448. When we added the latest version of MatterOverdrive to the pack (wasn't previously in the pack) after a few seconds people get a fatal error and get disconnected. They then get the error instantly on rejoin from then on until the server is restarted at which point they can connect again for a few seconds until it starts again. Unfortunately this isnt a crash so the logs arent hugely useful but I can do any additional testing/troubleshooting you require. I tried a base build with forge 1448 and just MatterOverdrive and didnt experience the issue so I'm not sure where to go next to try and pin this down. Full mod list if it helps: http://www.technicpack.net/modpack/nuts-and-bolts-alpha.561420/mods

**Comment by shadowfacts** [comment]
The logs _are_ hugely useful, please post them.

**Comment by Saereth** [comment]
Set it all up again to test, just seems to timeout now with matter overdrive installed. Had several people test but this log just shows me connect. 

Server log:
https://drive.google.com/file/d/0BwmxXoRAG3ddR05waFhOVHpfMnM/view?usp=sharing

Client log is pretty big but its here if needed: https://drive.google.com/file/d/0BwmxXoRAG3ddRXUxT0trSUk1VU0/view?usp=sharing

**Comment by simeonradivoev** [comment]
So this i happening just by adding matter overdrive ? I see a lot of errors from RF Tools, and none from matter overdrive.

**Comment by simeonradivoev** [comment]
'''
Attempting connection with missing mods [DeathCounter, Dynmap, eirairc, Morpheus, MapWriter, Opis, worldedit] at CLIENT
'''

'''
ava.lang.NullPointerException
	at mcjty.rftools.dimension.RfToolsDimensionManager.unregisterDimensions(RfToolsDimensionManager.java:96) ~[RfToolsDimensionManager.class:?]
	at mcjty.rftools.ClientDisconnectEvent.onDisconnectedFromServerEvent(ClientDisconnectEvent.java:14) ~[ClientDisconnectEvent.class:?]
'''

**Comment by Saereth** [comment]
the errors from rftools happen regardless but I'll remove rftools and test and get back to you shortly

**Comment by Saereth** [comment]
I removed rftools and mcjitycore dependency, still having the same issue. The missing mods are serverside only mods, well except for mapwriter/opis etc which are clientside optional.

**Comment by Saereth** [comment]
We update rftools and it cleared up all the issues, now we've got a cleaner logfile for you, the exact moment the fatal error/disconnects occur in the log is when it attempt to load an entity from MO:

[11:44:38] [Client thread/ERROR] [FML/]: There was a critical exception handling a packet on channel FML
java.lang.RuntimeException: Could not spawn mod entity ModID: mo EntityID: 70 at ( 54.5,36.0, 3.5) Please contact mod author or server admin.
	at cpw.mods.fml.common.network.internal.EntitySpawnHandler.spawnEntity(EntitySpawnHandler.java:64) ~[EntitySpawnHandler.class:?]
	at cpw.mods.fml.common.network.internal.EntitySpawnHandler.channelRead0(EntitySpawnHandler.java:34) ~[EntitySpawnHandler.class:?]
	at cpw.mods.fml.common.network.internal.EntitySpawnHandler.channelRead0(EntitySpawnHandler.java:28) ~[EntitySpawnHandler.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[MessageToMessageDecoder.class:?]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[MessageToMessageCodec.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273) [bje.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1602) [bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_60]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_60]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]

Full log is here: https://www.dropbox.com/s/xvtqfowq8hjm2ea/fml-client-latest.log?dl=1

**Comment by simeonradivoev** [comment]
The problem may come from the configs. Check and see if configs for the client and the server are the same. In particular check the entity IDs

**Comment by Keridos** [comment]
Having this as well, even with the same configs on both server and client. In a newly started world.

**Comment by simeonradivoev** [comment]
It seems I will have to remove the automatic entity ID correction and assign permanent entity IDs

**Comment by Alaberti** [comment]
I have seen this issue a lot on my mudpack/server - it occurs when the client and server have different entity ids from each other (typically the client will retain the default, but the server will have shifted slightly) and you appear where a spawn should be (ie rogue android). Copying the client config to the server has alleviated this problem for me.
