### ISSUE TITLE
Crash on placing glass

### ISSUE THREAD

**Issue by TheNumenorean** [simeonradivoev/MatterOverdrive#268]
[22:45:44] [Client thread/INFO] [STDOUT/]: [net.minecraft.client.Minecraft:func_71377_b:349]: ---- Minecraft Crash Report ----
// There are four lights!

Time: 10/11/15 10:45 PM
Description: Unexpected error

java.lang.NoSuchMethodError: matteroverdrive.blocks.ForceGlass.checkEIO(Lnet/minecraft/world/IBlockAccess;Lnet/minecraft/block/Block;III)Z
	at matteroverdrive.blocks.ForceGlass.func_149646_a(ForceGlass.java:84)
	at net.minecraft.client.renderer.RenderBlocks.func_147751_a(RenderBlocks.java:4334)
	at net.minecraft.client.renderer.RenderBlocks.func_147784_q(RenderBlocks.java:4247)
	at net.minecraft.client.renderer.RenderBlocks.func_147805_b(RenderBlocks.java:255)
	at net.minecraft.client.renderer.WorldRenderer.func_147892_a(WorldRenderer.java:181)
	at cofh.tweak.asmhooks.render.RenderGlobal.func_72716_a(RenderGlobal.java:99)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1187)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1011)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

Occurs when placing tritanium glass.

**Comment by simeonradivoev** [comment]
Duplicate #231

**Comment by shadowfacts** [comment]
Once the CI finishes, you'll be able to use build 127 (download [here](http://simeon.co.vu/Mods/MatterOverdrive/builds/)).
