### ISSUE TITLE
Major Performance issue with big tile entity lists

### ISSUE THREAD

**Issue by Slind14** [simeonradivoev/MatterOverdrive#272]
Hey,

the way the tile ent ticks are being dealt with is causing major trouble once the tile entity amount gets to a reasonable size. I would like to recommend on building a custom list only containing the relevant tile entities or a complete refactor to avoid the custom iteration over all. Though a custom list might be less work and wouldn't require major changes. It would need to be kept updated on chunk load/unload.. 

https://i.imgur.com/eTazqZb.png

**Comment by Badcholo** [comment]
What program are you using to see that?

**Comment by shadowfacts** [comment]
@Badcholo, looks like VisualVM, but any Java profiler could be used to obtain the same information.

**Comment by Badcholo** [comment]
Thanks.

**Comment by simeonradivoev** [comment]
Tracking my own loaded tile entities would be too much of a hassle, and there will be to much room for new bugs. The problem wasn't that the list got too big. The problem was that I iterated that list more than once, 4 times if I'm not mistaken. I might be totally wrong, but do try the fix and report back.

**Comment by Slind14** [comment]
Thank you, I assume that does reduce the time by about half. Might I ask why you are not using the forge tile entity tick, you wouldn't need any iteration, the only one happening would be the one from forge which is there anyways? 
I will test the new version to get more details, but I doubt it will be fairly enough optimization considering this: horizons modpack, matter overdrive not in the top 20 mods by tile entities, matter overdrive using +50% of the entire resource just for the iteration.

**Comment by simeonradivoev** [comment]
It's just that the Matter Network and the Gravitational anomaly require 2 stage ticks. That means a start and an end. The fix should reduce the performance drop by more than 4 times. That's like 75%. If the fix doesn't work I'll try and use the Tile Entity's own update.

**Comment by Slind14** [comment]
One more thought I just had. What about creating the list on the (tile)Entity Tick and iterating it once at the end of the world tick?

**Comment by Badcholo** [comment]
I know this isn't the place, but i installed VisualVM, i got about this far. Can you just let me know if there is anything irregular? when i use worldedit to edit a big area, even thou i have 16gb of ram, it doesn't use it all and i get timed out. i can't tell where my issue is at. maybe hard drive speed?
![capture](https://cloud.githubusercontent.com/assets/10932905/10627222/9cf80b40-776b-11e5-9b52-7f7998b59fca.PNG)
![capture2](https://cloud.githubusercontent.com/assets/10932905/10627227/a1dcf986-776b-11e5-93b1-509a043ed4eb.PNG)

**Comment by Badcholo** [comment]
This is on my server tower. It is separate from my computer and is connected directly to the modem. All other computers are connected to a smart gigabit switch. It's where i run my Mojangsters Server.

**Comment by simeonradivoev** [comment]
You may need to allocate more ram to Java. Or the timeout is just the server takes a long time to think about it. That's when you get a timeout message in minecraft.

**Comment by Slind14** [comment]
More ram does not give your CPU an upgrade.

**Comment by Slind14** [comment]
I could not really test as all those more up to date versions end up with the following 20 times a second ```
[03:08:28] [Server thread/ERROR]: Where was a problem while trying to get task from Queue from class matteroverdrive.machines.analyzer.components.MatterNetworkComponentAnalyzer
java.lang.ClassCastException: matteroverdrive.matter_network.tasks.MatterNetworkTaskReplicatePattern cannot be cast to matteroverdrive.matter_network.tasks.MatterNetworkTaskStorePattern
	at matteroverdrive.machines.analyzer.components.MatterNetworkComponentAnalyzer.manageTopQueue(MatterNetworkComponentAnalyzer.java:44) ~[MatterNetworkComponentAnalyzer.class:?]
	at matteroverdrive.matter_network.components.MatterNetworkComponentClientDispatcher.onNetworkTick(MatterNetworkComponentClientDispatcher.java:60) [MatterNetworkComponentClientDispatcher.class:?]
	at matteroverdrive.machines.analyzer.components.MatterNetworkComponentAnalyzer.onNetworkTick(MatterNetworkComponentAnalyzer.java:107) [MatterNetworkComponentAnalyzer.class:?]
	at matteroverdrive.machines.analyzer.TileEntityMachineMatterAnalyzer.onNetworkTick(TileEntityMachineMatterAnalyzer.java:294) [TileEntityMachineMatterAnalyzer.class:?]
	at matteroverdrive.handler.MatterNetworkTickHandler.updateHandler(MatterNetworkTickHandler.java:45) [MatterNetworkTickHandler.class:?]
	at matteroverdrive.handler.TickHandler.onWorldTick(TickHandler.java:106) [TickHandler.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_167_TickHandler_onWorldTick_WorldTickEvent.invoke(.dynamic) [?:1.7.10-1492.152]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) [ASMEventHandler.class:1.7.10-1492.152]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:1.7.10-1492.152]
	at cpw.mods.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:272) [FMLCommonHandler.class:1.7.10-1492.152]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:925) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
```

**Comment by simeonradivoev** [comment]
You're the second person to show that error and I still don't know why it's happening. How does a MatterNetworkTaskStorePattern task gets its way to a Matter Analyzer. It maybe a NBT loading error or something. The good news is that not if something like this happens It won't persist for that long.
Should be fixed by b712c1ead34e93289cf849c90f1fdb10bf5eefb9. You can try out the build 138.

**Comment by Slind14** [comment]
all good with 138, thank you @simeonradivoev

**Comment by simeonradivoev** [comment]
good to hear !
