### ISSUE TITLE
Console spam and several minute bootup with latest version

### ISSUE THREAD

**Issue by Saereth** [simeonradivoev/MatterOverdrive#290]
We are running build 1.7.10-0.4.0-RC4-build-139 and now when we boot the server we see a ton of spam like this for a couple minutes delaying the server from starting. It doesnt actually crash or anything though...

java.lang.NullPointerException
        at net.minecraft.item.ItemStack.func_77960_j(ItemStack.java:243) ~[add.class:?]
        at matteroverdrive.handler.MatterRegistry.getOreDicionaryEntry(MatterRegistry.java:333) ~[MatterRegistry.class:?]
        at matteroverdrive.handler.MatterRegistry.getEntry(MatterRegistry.java:294) [MatterRegistry.class:?]
        at matteroverdrive.handler.MatterRegistry.getMatterFromList(MatterRegistry.java:467) [MatterRegistry.class:?]
        at matteroverdrive.handler.MatterRegistry.getMatterFromRecipe(MatterRegistry.java:372) [MatterRegistry.class:?]
        at matteroverdrive.handler.thread.RegisterItemsFromRecipes.run(RegisterItemsFromRecipes.java:82) [RegisterItemsFromRecipes.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_51]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_51]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_51]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_51]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]

**Comment by simeonradivoev** [comment]
Do you have the matter calculation debug option in the config set to true ?

**Comment by Saereth** [comment]
Not we havent changed anything in the configs other than the enchantment id

##########################################################################################################
# debug
#--------------------------------------------------------------------------------------------------------#
# Debug Options. Such as Debug Log for Matter Recipe Calculation
##########################################################################################################

debug {
    B:"matter calculation"=false
    B:"matter registation"=false
}

**Comment by Towsty** [comment]
I have the same issues in 0.4.0 as well.

**Comment by Towsty** [comment]
I am seeing the same spam it seems with 0.4.0:

https://www.dropbox.com/s/2etzpdu5xus8nom/fml-server-3.log?dl=0
