### ISSUE TITLE
In-game config doesn't open

### ISSUE THREAD

**Issue by Alaberti** [simeonradivoev/MatterOverdrive#316]
When I try to open the config in game, I get this error in the console log:

```
[B#328]  [15:10:40] [Client thread/ERROR] [FML]: There was a critical issue trying to build the config GUI for mo
[B#328]  java.lang.NoSuchMethodException: matteroverdrive.gui.GuiConfig.<init>(net.minecraft.client.gui.GuiScreen)
[B#328]  	at java.lang.Class.getConstructor0(Unknown Source) ~[?:1.8.0_60]
[B#328]  	at java.lang.Class.getConstructor(Unknown Source) ~[?:1.8.0_60]
[B#328]  	at cpw.mods.fml.client.GuiModList.func_146284_a(GuiModList.java:121) [GuiModList.class:?]
[B#328]  	at com.enderio.core.client.gui.bettermodlist.GuiEnhancedModList.func_146284_a(GuiEnhancedModList.java:271) [GuiEnhancedModList.class:?]
[B#328]  	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:225) [bdw.class:?]
[B#328]  	at com.enderio.core.client.gui.bettermodlist.GuiEnhancedModList.func_73864_a(GuiEnhancedModList.java:216) [GuiEnhancedModList.class:?]
[B#328]  	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296) [bdw.class:?]
[B#328]  	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268) [bdw.class:?]
[B#328]  	at net.minecraft.client.Minecraft.func_71407_l(Unknown Source) [bao.class:?]
[B#328]  	at net.minecraft.client.Minecraft.func_71411_J(Unknown Source) [bao.class:?]
[B#328]  	at net.minecraft.client.Minecraft.func_99999_d(Unknown Source) [bao.class:?]
[B#328]  	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
[B#328]  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
[B#328]  	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_60]
[B#328]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_60]
[B#328]  	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_60]
[B#328]  	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
[B#328]  	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
```

**Comment by simeonradivoev** [comment]
It's seems to be a bettermodlist error

**Comment by Alaberti** [comment]
I think that's just a handler; from what I can tell, it's trying to call a gui method from your mod that doesn't exist - I'm not sure if this is an API thing you need to enable or not.

**Comment by simeonradivoev** [comment]
No idea but matteroverdrive.gui.GuiConfig is definitely there.

**Comment by Alaberti** [comment]
That awkward moment.

**Comment by tterrag1098** [comment]
It's crashing due to a missing method, not class. Your GuiConfig *needs* to have a constructor which takes only a GuiScreen.

**Comment by tterrag1098** [comment]
Also, this has nothing to do with EnderCore, if you notice the last line before it enters your code is in FML.

**Comment by simeonradivoev** [comment]
Ah yes, my bad.
