### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by PalePyth** [simeonradivoev/MatterOverdrive#332]
```
---- Minecraft Crash Report ----
// Why did you do that?

Time: 22.11.15 20:03
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: matteroverdrive/blocks/BlockReplicator
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:559)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: matteroverdrive/blocks/BlockReplicator
	at matteroverdrive.init.MatterOverdriveBlocks.init(MatterOverdriveBlocks.java:90)
	at matteroverdrive.MatterOverdrive.preInit(MatterOverdrive.java:102)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
	... 10 more
Caused by: java.lang.ClassNotFoundException: matteroverdrive.blocks.BlockReplicator
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 38 more
Caused by: java.lang.NoClassDefFoundError: matteroverdrive/blocks/includes/MOMatterEnergyStorageBlock
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 40 more
Caused by: java.lang.ClassNotFoundException: matteroverdrive.blocks.includes.MOMatterEnergyStorageBlock
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 44 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_45, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 292313032 bytes (278 MB) / 704139264 bytes (671 MB) up to 2134114304 bytes (2035 MB)
	JVM Flags: 11 total; -XX:HeapDumpPath=ThisTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2048M -Xmn128M -XX:+UseConcMarkSweepGC -XX:-UseAdaptiveSizePolicy -XX:-UseGCOverheadLimit -XX:+CMSParallelRemarkEnabled -XX:+ParallelRefProcEnabled -XX:+CMSClassUnloadingEnabled -XX:+UseCMSInitiatingOccupancyOnly -Xms256M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1492 96 mods loaded, 95 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1492-1.7.10.jar) 
	UCH	Forge{10.13.4.1492} [Minecraft Forge] (forge-1.7.10-10.13.4.1492-1.7.10.jar) 
	UCH	appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core] (minecraft.jar) 
	UCH	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCH	itemphysic{1.1.5} [ItemPhysic] (minecraft.jar) 
	UCH	MobiusCore{1.2.5} [MobiusCore] (minecraft.jar) 
	UCH	NotEnoughItems{1.0.5.111} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.111-universal.jar) 
	UCH	OpenComputers|Core{1.5.18.36} [OpenComputers (Core)] (minecraft.jar) 
	UCH	modJ_StarMinerCore{0.9.9} [StarMinerCore] (minecraft.jar) 
	UCH	IC2{2.2.791-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.791-experimental.jar) 
	UCH	ImmibisCore{59.1.2} [Immibis Core] (immibis-core-59.1.2.jar) 
	UCH	AdvancedRepulsionSystems{59.0.3} [Advanced Repulsion Systems] (adv-repulsion-systems-59.0.3.jar) 
	UCH	AgriCraft{1.7.10-1.4.3} [AgriCraft] (AgriCraft-1.7.10-1.4.3.jar) 
	UCH	AppleCore{1.1.0} [AppleCore] (AppleCore-mc1.7.10-1.1.0.jar) 
	UCH	appliedenergistics2{rv2-stable-10} [Applied Energistics 2] (appliedenergistics2-rv2-stable-10.jar) 
	UCH	Forestry{4.1.1.46} [Forestry for Minecraft] (forestry_1.7.10-4.1.1.46.jar) 
	UCH	harvestcraft{1.7.10j} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10j.jar) 
	UCH	gregtech{MC1710} [GregTech] (gregtech-5.09.11.jar) 
	UCH	asielib{0.4.2} [asielib] (AsieLib-1.7.10-0.4.2.jar) 
	UCH	bdlib{1.9.3.107} [BD Lib] (bdlib-1.9.3.107-mc1.7.10.jar) 
	UCH	betterstorage{0.13.1.127} [BetterStorage] (BetterStorage-1.7.10-0.13.1.127.jar) 
	UCH	BiomeTweaker{1.2.128} [BiomeTweaker] (BiomeTweaker-1.7.10-1.2.128.jar) 
	UCH	CarpentersBlocks{3.3.7} [Carpenter's Blocks] (Carpenter's Blocks v3.3.7 - MC 1.7.10.jar) 
	UCH	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCH	chisel{2.5.1.44} [Chisel 2] (Chisel2-2.5.1.44.jar) 
	UCH	OpenComputers{1.5.18.36} [OpenComputers] (OpenComputers-MC1.7.10-1.5.18.36-universal.jar) 
	UCH	MrTJPCoreMod{1.1.0.31} [MrTJPCore] (MrTJPCore-1.1.0.31-universal.jar) 
	UCH	ProjRed|Core{4.7.0pre9.92} [ProjectRed Core] (ProjectRed-1.7.10-4.7.0pre9.92-Base.jar) 
	UCH	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCH	computronics{1.5.7} [Computronics] (Computronics-1.7.10-1.5.7.jar) 
	UCH	cookingbook{1.0.128} [Cooking for Blockheads] (cookingbook-mc1.7.10-1.0.128.jar) 
	UCH	BuildMod{v1.0} [Build Mod] (coroutil-1.1.3 for MC v1.7.10.jar) 
	UCH	CoroPets{v1.0} [CoroPets] (coroutil-1.1.3 for MC v1.7.10.jar) 
	UCH	CoroAI{v1.0} [CoroAI] (coroutil-1.1.3 for MC v1.7.10.jar) 
	UCH	ExtendedRenderer{v1.0} [Extended Renderer] (coroutil-1.1.3 for MC v1.7.10.jar) 
	UCH	ConfigMod{v1.0} [Extended Mod Config] (coroutil-1.1.3 for MC v1.7.10.jar) 
	UCH	creativecore{1.3.14} [CreativeCore] (CreativeCore v1.3.14 mc1.7.10.jar) 
	UCH	CustomMainMenu{1.9.2} [Custom Main Menu] (CustomMainMenu-MC1.7.10-1.9.2.jar) 
	UCH	Dynmap{2.2-143} [Dynmap] (Dynmap-2.2-forge-1.7.10.jar) 
	UCH	ESM{10.0.131} [Epic Siege Mod] (EpicSiegeMod-10.0.131.jar) 
	UCH	extracells{2.2.73} [Extra Cells 2] (ExtraCells-1.7.10-2.2.73b129.jar) 
	UCH	FastCraft{1.21} [FastCraft] (fastcraft-1.21.jar) 
	UCH	fastleafdecay{1.3} [Fast Leaf Decay] (FastLeafDecay-1.7.10-1.3.jar) 
	UCH	flansmod{4.10.0} [Flan's Mod] (Flans Mod-1.7.10-4.10.0.jar) 
	UCH	ForgeRelocation{0.0.1.4} [ForgeRelocation] (ForgeRelocation-0.0.1.4-universal.jar) 
	UCH	MCFrames{1.0} [MCFrames] (ForgeRelocation-0.0.1.4-universal.jar) 
	UCH	RelocationFMP{0.0.1.2} [RelocationFMP] (ForgeRelocationFMP-1.7.10-0.0.1.2-universal.jar) 
	UCH	gendustry{1.6.2.127} [GenDustry] (gendustry-1.6.2.127-mc1.7.10.jar) 
	UCH	GP{0.1} [GP] (GP.jar) 
	UCH	GraviSuite{1.7.10-2.0.3} [Graviation Suite] (GraviSuite-1.7.10-2.0.3.jar) 
	UCH	GregsLighting{1.11.2} [Greg's Lighting] (GregsLighting-1.11.2-mc1.7.10.jar) 
	UCH	GTTweaker{1.0.9} [GTTweaker] (GTTweaker-1.7.10-1.0.9.jar) 
	UCH	HardcoreDarkness{1.7} [Hardcore Darkness] (HardcoreDarkness-MC1.7.10-1.7.jar) 
	UCH	HoloInventory{1.9.1.122} [HoloInventory] (HoloInventory-1.7.10-1.9.1.122.jar) 
	UCH	hungryanimals{1.7.10-10.13.2.1291-1.0.4.2} [Hungry Animals] (hungryanimals-1.0.4.2.beta015.jar) 
	UCH	IC2NuclearControl{2.2.5a-GoingForTheKill} [Nuclear Control 2] (IC2NuclearControl-2.2.5a-GoingForTheKill.jar) 
	UCH	LunatriusCore{1.1.2.21} [LunatriusCore] (LunatriusCore-1.7.10-1.1.2.21-universal.jar) 
	UCH	InGameInfoXML{2.8.1.82} [InGame Info XML] (InGameInfoXML-1.7.10-2.8.1.82-universal.jar) 
	UCH	inpure|core{1.7.10R1.0.0B9} [INpureCore] (INpureCore-[1.7.10]1.0.0B9-62.jar) 
	UCH	integratedcircuits{1.7.10-0.9r36} [Integrated Circuits] (integratedcircuits-1.7.10-0.9r36.jar) 
	UCH	JABBA{1.2.1} [JABBA] (Jabba-1.2.1a_1.7.10.jar) 
	UCH	LavaMonsters{2.2.1} [Lava Monsters] (LavaMonsters-1.7.10-2.2.1.jar) 
	UCE	mo{0.4.0-RC4} [Matter Overdrive] (MatterOverdrive-1.7.10-0.4.0.jar) 
	UCH	MineTweaker3{3.0.10} [MineTweaker 3] (MineTweaker3-1.7.10-3.0.10B.jar) 
	UCH	modtweaker2{0.9.4} [Mod Tweaker 2] (ModTweaker2-0.9.4.jar) 
	UCH	numina{0.4.0.100} [Numina] (Numina-0.4.0.100.jar) 
	UCH	powersuits{0.11.0.177} [MachineMuse's Modular Powersuits] (ModularPowersuits-0.11.0.177.jar) 
	UCH	Morpheus{1.7.10-1.6.10} [Morpheus] (Morpheus-1.7.10-1.6.10.jar) 
	UCH	NEIAddons{1.12.14.40} [NEI Addons] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCH	NEIAddons|Developer{1.12.14.40} [NEI Addons: Developer Tools] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCH	NEIAddons|AppEng{1.12.14.40} [NEI Addons: Applied Energistics 2] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCH	NEIAddons|Botany{1.12.14.40} [NEI Addons: Botany] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCH	NEIAddons|Forestry{1.12.14.40} [NEI Addons: Forestry] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCH	NEIAddons|CraftingTables{1.12.14.40} [NEI Addons: Crafting Tables] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCH	NEIAddons|ExNihilo{1.12.14.40} [NEI Addons: Ex Nihilo] (neiaddons-1.12.14.40-mc1.7.10.jar) 
	UCH	notenoughkeys{@MOD_VERSION@} [NotEnoughKEys] (NotEnoughKeys-1.7.10-1.0.0b30.jar) 
	UCH	openmodularturrets{2.1.3-163} [Open Modular Turrets] (OpenModularTurrets-1.7.10-2.1.3-163.jar) 
	UCH	ProjRed|Illumination{4.7.0pre9.92} [ProjectRed Illumination] (ProjectRed-1.7.10-4.7.0pre9.92-Lighting.jar) 
	UCH	RealisticTorches{1.3.0} [Realistic Torches] (RealisticTorches-1.7.10-1.3.0.jar) 
	UCH	ResourceLoader{1.2} [Resource Loader] (ResourceLoader-1.2.jar) 
	UCH	corerm{1.0c} [RikMuld's Core] (RikMuldsCore_1.0c.jar) 
	UCH	simplefluidtanks{1.7.10-1.2.0.5} [Simple Fluid Tanks] (simplefluidtanks-1.7.10-1.2.0.5.jar) 
	UCH	SpiceOfLife{1.2.4} [The Spice of Life] (SpiceOfLife-mc1.7.10-1.2.4.jar) 
	UCH	modJ_StarMiner{0.9.9} [Starminer Mod] (Starminer1710-0.9.9.jar) 
	UCH	StevesCarts{2.0.0.b18} [Steve's Carts 2] (StevesCarts2.0.0.b18.jar) 
	UCH	StevesFactoryManager{A93} [Steve's Factory Manager] (StevesFactoryManagerA93.jar) 
	UCH	camping{2.1g} [The Camping Mod 2] (TheCampingMod_2.1g.jar) 
	UCH	toolbox{1.2.3} [Toolbox] (Toolbox-1.7.10-1.2.3.jar) 
	UCH	Trapcraft{v2.2.1a} [Trapcraft] (Trapcraft-Mod.zip) 
	UCH	weather2{v2.3.10} [Localized Weather & Storms] (weather2-2.3.10 for MC v1.7.10.jar) 
	UCH	bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar) 
	UCH	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCH	HungerOverhaul{1.7.10-1.0.0.jenkins75} [Hunger Overhaul] (HungerOverhaul-1.7.10-1.0.0.jar) 
	UCH	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UD	BiomeTweakerCore{1.2.128} [BiomeTweaker Core] (minecraft.jar) 
	GL info: ' Vendor: 'Intel' Version: '4.3.0 - Build 10.18.14.4264' Renderer: 'Intel(R) HD Graphics 4600'
	AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
	List of loaded APIs: 
		* AgriCraftAPI (1.0) from AgriCraft-1.7.10-1.4.3.jar
		* API_NEK (1.0.0) from NotEnoughKeys-1.7.10-1.0.0b30.jar
		* AppleCoreAPI (1.1.0) from AppleCore-mc1.7.10-1.1.0.jar
		* appliedenergistics2|API (rv2) from appliedenergistics2-rv2-stable-10.jar
		* asielibAPI (1.1) from AsieLib-1.7.10-0.4.2.jar
		* asielibAPI|chat (1.0) from AsieLib-1.7.10-0.4.2.jar
		* asielibAPI|tile (1.0) from AsieLib-1.7.10-0.4.2.jar
		* asielibAPI|tool (1.1) from AsieLib-1.7.10-0.4.2.jar
		* BuildCraftAPI|tools (1.0) from simplefluidtanks-1.7.10-1.2.0.5.jar
		* CarpentersBlocks|API (3.3.7) from Carpenter's Blocks v3.3.7 - MC 1.7.10.jar
		* ChiselAPI (0.1.0) from Chisel2-2.5.1.44.jar
		* ChiselAPI|Carving (0.1.0) from Chisel2-2.5.1.44.jar
		* ChiselAPI|Rendering (0.1.0) from Chisel2-2.5.1.44.jar
		* CoFHAPI (1.7.10R1.0.2) from IC2NuclearControl-2.2.5a-GoingForTheKill.jar
		* CoFHAPI|energy (1.7.10R1.0.2) from forestry_1.7.10-4.1.1.46.jar
		* computronicsAPI (1.3) from Computronics-1.7.10-1.5.7.jar
		* computronicsAPI|chat (1.3) from Computronics-1.7.10-1.5.7.jar
		* computronicsAPI|multiperipheral (1.1) from Computronics-1.7.10-1.5.7.jar
		* computronicsAPI|tape (1.0) from Computronics-1.7.10-1.5.7.jar
		* ForestryAPI|apiculture (4.4.1) from forestry_1.7.10-4.1.1.46.jar
		* ForestryAPI|arboriculture (4.2.1) from forestry_1.7.10-4.1.1.46.jar
		* ForestryAPI|circuits (3.1.0) from forestry_1.7.10-4.1.1.46.jar
		* ForestryAPI|core (5.0.0) from forestry_1.7.10-4.1.1.46.jar
		* ForestryAPI|farming (2.0.0) from forestry_1.7.10-4.1.1.46.jar
		* ForestryAPI|food (1.1.0) from forestry_1.7.10-4.1.1.46.jar
		* ForestryAPI|fuels (2.0.1) from forestry_1.7.10-4.1.1.46.jar
		* ForestryAPI|genetics (4.4.0) from forestry_1.7.10-4.1.1.46.jar
		* ForestryAPI|hives (4.1.0) from forestry_1.7.10-4.1.1.46.jar
		* ForestryAPI|lepidopterology (1.3.0) from forestry_1.7.10-4.1.1.46.jar
		* ForestryAPI|mail (3.0.0) from forestry_1.7.10-4.1.1.46.jar
		* ForestryAPI|recipes (5.4.0) from forestry_1.7.10-4.1.1.46.jar
		* ForestryAPI|storage (3.0.0) from forestry_1.7.10-4.1.1.46.jar
		* ForestryAPI|world (2.1.0) from forestry_1.7.10-4.1.1.46.jar
		* ForgeRelocation|API (0.0.1.4) from ForgeRelocation-0.0.1.4-universal.jar
		* gendustryAPI (2.3.0) from gendustry-1.6.2.127-mc1.7.10.jar
		* IC2API (1.0) from industrialcraft-2-2.2.791-experimental.jar
		* inpure|api (1.7) from INpureCore-[1.7.10]1.0.0B9-62.jar
		* integratedcircuits|API (0.1) from integratedcircuits-1.7.10-0.9r36.jar
		* MatterOverdrive|API (0.4.0) from MatterOverdrive-1.7.10-0.4.0.jar
		* NuclearControlAPI (v1.0.5) from IC2NuclearControl-2.2.5a-GoingForTheKill.jar
		* OpenComputersAPI|Component (5.6.2) from OpenComputers-MC1.7.10-1.5.18.36-universal.jar
		* OpenComputersAPI|Core (5.6.2) from OpenComputers-MC1.7.10-1.5.18.36-universal.jar
		* OpenComputersAPI|Driver (5.6.2) from OpenComputers-MC1.7.10-1.5.18.36-universal.jar
		* OpenComputersAPI|Driver|Item (5.6.2) from OpenComputers-MC1.7.10-1.5.18.36-universal.jar
		* OpenComputersAPI|Event (5.6.2) from OpenComputers-MC1.7.10-1.5.18.36-universal.jar
		* OpenComputersAPI|FileSystem (5.6.2) from OpenComputers-MC1.7.10-1.5.18.36-universal.jar
		* OpenComputersAPI|Internal (5.6.2) from OpenComputers-MC1.7.10-1.5.18.36-universal.jar
		* OpenComputersAPI|Machine (5.6.2) from OpenComputers-MC1.7.10-1.5.18.36-universal.jar
		* OpenComputersAPI|Manual (5.6.2) from OpenComputers-MC1.7.10-1.5.18.36-universal.jar
		* OpenComputersAPI|Network (5.6.2) from OpenComputers-MC1.7.10-1.5.18.36-universal.jar
		* OpenComputersAPI|Prefab (5.6.2) from OpenComputers-MC1.7.10-1.5.18.36-universal.jar
		* StarminerAPI (0.9.8) from Starminer1710-0.9.9.jar
		* Thaumcraft|API (4.2.0.0) from Pam's HarvestCraft 1.7.10j.jar
		* WailaAPI (1.2) from Waila-1.5.10_1.7.10.jar
```

**Comment by shadowfacts** [comment]
CoFHLib is required.
