### ISSUE TITLE
Server unresponsive after trying to generate structures

### ISSUE THREAD

**Issue by Mysteryem** [simeonradivoev/MatterOverdrive#353]
For starters, this is with build 181, with the integrated server (singleplayer) and as part of a modpack. I can't tell if it always locks up when trying to generate these, but so far it's locked up once when trying to generate structures as part of the spawn chunks ("preparing spawn" never made it past 80%) and a second time during mystcraft's baseline profiling.

I used jstack to get stacktraces of the server thread to see what was going on. It looks like either there is an infinite loop or a loop that is taking a very long time to complete. In the second instance I gave up after waiting for just over 2 minutes and killed the process.

Server thread stacktraces: https://gist.github.com/Mysteryem/5ad4c13558148618ddbd

For quick reference, func_149747_d(...) is isBlockSolid(...), func_147439_a(...) is getBlock(...) and func_72964_e(...) is getChunkFromChunkCoords(...)

I was working on an update to my private modpack and seeing if the new dev build might be a possible candidate for the update seeing as it has new world generation. After I'm done with this modpack update I can explore this issue more if it's still needed at that time (remove mods to verify it's just Matter Overdrive causing this or determine which combination of mods are culprit etc.).

**Comment by shadowfacts** [comment]
Can you attempt to reproduce this without Fastcraft? It does some funky stuff and can sometimes cause problems with other mods.

**Comment by Mysteryem** [comment]
Yeah, took a little longer for it to happen this time (guessing a coincidence). Again mystcraft generating chunks got it to happen.

Example trace with no fastcraft (I did take a number of other stack traces to ensure that it was still actually doing something):
```
"Server thread" #641 prio=5 os_prio=0 tid=0x00000000435a9800 nid=0x2b94 runnable [0x000000002b68d000]
   java.lang.Thread.State: RUNNABLE
	at net.minecraft.world.World.func_72964_e(World.java:419)
	at net.minecraft.world.World.func_147439_a(World.java:345)
	at net.minecraft.block.BlockLiquid.func_149747_d(BlockLiquid.java:128)
	at matteroverdrive.world.MOWorldGenUnderwaterBase.isPointDeepEnough(MOWorldGenUnderwaterBase.java:113)
	at matteroverdrive.world.MOWorldGenUnderwaterBase.isLocationValid(MOWorldGenUnderwaterBase.java:100)
	at matteroverdrive.world.WeightedRandomMOWorldGenBuilding.getWeight(WeightedRandomMOWorldGenBuilding.java:41)
	at matteroverdrive.world.MOWorldGen.getTotalBuildingsWeight(MOWorldGen.java:219)
	at matteroverdrive.world.MOWorldGen.getRandomBuilding(MOWorldGen.java:211)
	at matteroverdrive.world.MOWorldGen.startGenerateBuildings(MOWorldGen.java:188)
	at matteroverdrive.world.MOWorldGen.generate(MOWorldGen.java:111)
	at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:112)
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:280)
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1055)
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190)
	at com.xcompwiz.mystcraft.world.profiling.WorldProviderMystDummy$ChunkProviderServerDummy.originalLoadChunk(WorldProviderMystDummy.java:62)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
	at com.xcompwiz.mystcraft.world.profiling.WorldProviderMystDummy.generateNextChunk(WorldProviderMystDummy.java:217)
	at com.xcompwiz.mystcraft.world.profiling.InstabilityDataCalculator.stepChunkGeneration(InstabilityDataCalculator.java:343)
	at com.xcompwiz.mystcraft.world.profiling.InstabilityDataCalculator.onServerTick(InstabilityDataCalculator.java:180)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_2277_InstabilityDataCalculator_onServerTick_ServerTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:247)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:590)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

Interestingly, the client changed to the 'shutting down server' screen and then locked up itself, I'm guessing it was waiting on the server to wake it up from sleep as its thread state was TIMED_WAITING (sleeping) rather than WAITING (on object monitor) or TIMED_WAITING (on object monitor).

**Comment by Mysteryem** [comment]
Spent about 2 hours flying around and letting mystcraft do its thing for a few different worlds, it seems your fix has done the job.

I didn't find any underwater bases mind you, though I don't really know what I'm looking for.

**Comment by simeonradivoev** [comment]
The spawn in ocean biomes. In deep waters.
