### ISSUE TITLE
Client Crash (gravitational anomaly block)

### ISSUE THREAD

**Issue by SirWilli** [simeonradivoev/MatterOverdrive#36]
Changing the option B:"gravitational anomaly falling blocks"=true to false crashes the client if you load the gravitational anomaly block.
```
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at cofh.lib.util.helpers.BlockHelper.createStackedBlock(BlockHelper.java:542)
	at com.MO.MatterOverdrive.tile.TileEntityGravitationalAnomaly.brakeBlock(TileEntityGravitationalAnomaly.java:470)
	at com.MO.MatterOverdrive.tile.TileEntityGravitationalAnomaly.manageBlockDestory(TileEntityGravitationalAnomaly.java:361)
	at com.MO.MatterOverdrive.tile.TileEntityGravitationalAnomaly.onServerTick(TileEntityGravitationalAnomaly.java:261)
	at com.MO.MatterOverdrive.handler.TickHandler.onWorldTick(TickHandler.java:94)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_231_TickHandler_onWorldTick_WorldTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:255)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:645)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

**Comment by simeonradivoev** [comment]
It seems it's a cofhlib problem. I will have to do it myself.
