### ISSUE TITLE
NPE between Reika's mods and MatterOverdriveHandler

### ISSUE THREAD

**Issue by viper2g1** [simeonradivoev/MatterOverdrive#382]
I tried to update to the latest version released today (0.4.1) and also install Electricraft.  I immediately got erros and narrowed it down to the new version of Matter Overdrive.  With Electricraft installed and the server running fine using Matter Overdrive (0.4.0) I try to install the 0.4.1 version and I get errors.  I tried with and without CoFHLib since I saw it's dependency was removed.  

These issues only arrise when I try to include the new version of Matter Overdrive.

Here is the error that I get:

    [09:54:59] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.NullPointerException
    [09:54:59] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
    [09:54:59] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    [09:54:59] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
    [09:54:59] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at Reika.DragonAPI.ModInteract.DeepInteract.MatterOverdriveHandler.blacklist(MatterOverdriveHandler.java:31)
    [09:54:59] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at Reika.DragonAPI.ModInteract.DeepInteract.SensitiveItemRegistry$Interactions.blacklist(SensitiveItemRegistry.java:110)
    [09:54:59] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at Reika.DragonAPI.ModInteract.DeepInteract.SensitiveItemRegistry$Interactions.access$300(SensitiveItemRegistry.java:70)
    [09:54:59] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at Reika.DragonAPI.ModInteract.DeepInteract.SensitiveItemRegistry.registerItem(SensitiveItemRegistry.java:52)
    [09:54:59] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at Reika.ElectriCraft.ElectriCraft.load(ElectriCraft.java:181)
    [09:54:59] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    [09:54:59] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    [09:54:59] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    [09:54:59] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
    [09:54:59] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
    [09:54:59] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
    [09:54:59] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    [09:54:59] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
    [09:54:59] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    [09:54:59] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    [09:54:59] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    [09:54:59] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    [09:54:59] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    [09:54:59] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
    [09:54:59] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
    [09:54:59] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:737)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:319)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:210)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.NullPointerException
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at Reika.DragonAPI.ModInteract.DeepInteract.MatterOverdriveHandler.blacklist(MatterOverdriveHandler.java:31)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at Reika.DragonAPI.ModInteract.DeepInteract.SensitiveItemRegistry$Interactions.blacklist(SensitiveItemRegistry.java:110)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at Reika.DragonAPI.ModInteract.DeepInteract.SensitiveItemRegistry$Interactions.access$300(SensitiveItemRegistry.java:70)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at Reika.DragonAPI.ModInteract.DeepInteract.SensitiveItemRegistry.registerItem(SensitiveItemRegistry.java:52)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at Reika.ElectriCraft.ElectriCraft.load(ElectriCraft.java:182)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:737)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:319)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:210)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.NullPointerException
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at Reika.DragonAPI.ModInteract.DeepInteract.MatterOverdriveHandler.blacklist(MatterOverdriveHandler.java:31)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at Reika.DragonAPI.ModInteract.DeepInteract.SensitiveItemRegistry$Interactions.blacklist(SensitiveItemRegistry.java:110)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at Reika.DragonAPI.ModInteract.DeepInteract.SensitiveItemRegistry$Interactions.access$300(SensitiveItemRegistry.java:70)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at Reika.DragonAPI.ModInteract.DeepInteract.SensitiveItemRegistry.registerItem(SensitiveItemRegistry.java:52)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at Reika.ElectriCraft.ElectriCraft.load(ElectriCraft.java:183)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:737)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:319)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:210)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
    [09:55:00] [Server thread/INFO] [STDERR/ElectriCraft]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by simeonradivoev** [comment]
It's a problem with DragonAPI not Matter Overdrive. The API they call is old. You should tell them to use the IMC calls to blacklist items easily.

**Comment by ReikaKalseki** [comment]
My question [here](https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/553) has as yet gone unanswered.
