### ISSUE TITLE
freeze when flying into a massive anomaly

### ISSUE THREAD

**Issue by shadoxxhd** [simeonradivoev/MatterOverdrive#412]
```
There was an Error while updating Matter Overdrive Tile Entities.
java.lang.ArrayIndexOutOfBoundsException: 410
	at net.minecraft.enchantment.EnchantmentHelper.func_77518_a(EnchantmentHelper.java:153) ~[afv.class:?]
	at net.minecraft.enchantment.EnchantmentHelper.func_77516_a(EnchantmentHelper.java:170) ~[afv.class:?]
	at net.minecraft.enchantment.EnchantmentHelper.func_77508_a(EnchantmentHelper.java:178) ~[afv.class:?]
	at com.emoniph.witchery.util.EntityUtil.getHealthAfterDamage(EntityUtil.java:354) ~[EntityUtil.class:?]
	at com.emoniph.witchery.common.GenericEvents.onLivingHurt(GenericEvents.java:1231) ~[GenericEvents.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_1881_GenericEvents_onLivingHurt_LivingHurtEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:?]
	at net.minecraftforge.common.ForgeHooks.onLivingHurt(ForgeHooks.java:298) ~[ForgeHooks.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70665_d(EntityPlayer.java:1080) ~[yz.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:785) ~[sv.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70097_a(EntityPlayer.java:1034) ~[yz.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_70097_a(EntityPlayerMP.java:491) ~[mw.class:?]
	at matteroverdrive.tile.TileEntityGravitationalAnomaly.consumeLivingEntity(TileEntityGravitationalAnomaly.java:575) ~[TileEntityGravitationalAnomaly.class:?]
	at matteroverdrive.tile.TileEntityGravitationalAnomaly.consume(TileEntityGravitationalAnomaly.java:507) ~[TileEntityGravitationalAnomaly.class:?]
	at matteroverdrive.tile.TileEntityGravitationalAnomaly.manageEntityGravitation(TileEntityGravitationalAnomaly.java:243) ~[TileEntityGravitationalAnomaly.class:?]
	at matteroverdrive.tile.TileEntityGravitationalAnomaly.onServerTick(TileEntityGravitationalAnomaly.java:153) ~[TileEntityGravitationalAnomaly.class:?]
	at matteroverdrive.handler.TickHandler.onWorldTick(TickHandler.java:112) [TickHandler.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_743_TickHandler_onWorldTick_WorldTickEvent.invoke(.dynamic) [?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) [ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:?]
	at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:255) [FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:645) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) [bsx.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
[23:29:33] [Server thread/ERROR] [FML/]: Exception caught during firing event net.minecraftforge.event.entity.living.LivingHurtEvent@26fa9bf1:
java.lang.ArrayIndexOutOfBoundsException: 410
	at net.minecraft.enchantment.EnchantmentHelper.func_77518_a(EnchantmentHelper.java:153) ~[afv.class:?]
	at net.minecraft.enchantment.EnchantmentHelper.func_77516_a(EnchantmentHelper.java:170) ~[afv.class:?]
	at net.minecraft.enchantment.EnchantmentHelper.func_77508_a(EnchantmentHelper.java:178) ~[afv.class:?]
	at com.emoniph.witchery.util.EntityUtil.getHealthAfterDamage(EntityUtil.java:354) ~[EntityUtil.class:?]
	at com.emoniph.witchery.common.GenericEvents.onLivingHurt(GenericEvents.java:1231) ~[GenericEvents.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_1881_GenericEvents_onLivingHurt_LivingHurtEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:?]
	at net.minecraftforge.common.ForgeHooks.onLivingHurt(ForgeHooks.java:298) [ForgeHooks.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70665_d(EntityPlayer.java:1080) [yz.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:785) [sv.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70097_a(EntityPlayer.java:1034) [yz.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_70097_a(EntityPlayerMP.java:491) [mw.class:?]
	at matteroverdrive.tile.TileEntityGravitationalAnomaly.consumeLivingEntity(TileEntityGravitationalAnomaly.java:575) [TileEntityGravitationalAnomaly.class:?]
	at matteroverdrive.tile.TileEntityGravitationalAnomaly.consume(TileEntityGravitationalAnomaly.java:507) [TileEntityGravitationalAnomaly.class:?]
	at matteroverdrive.tile.TileEntityGravitationalAnomaly.manageEntityGravitation(TileEntityGravitationalAnomaly.java:243) [TileEntityGravitationalAnomaly.class:?]
	at matteroverdrive.tile.TileEntityGravitationalAnomaly.onServerTick(TileEntityGravitationalAnomaly.java:153) [TileEntityGravitationalAnomaly.class:?]
	at matteroverdrive.handler.TickHandler.onWorldTick(TickHandler.java:112) [TickHandler.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_743_TickHandler_onWorldTick_WorldTickEvent.invoke(.dynamic) [?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) [ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:?]
	at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:255) [FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:645) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) [bsx.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
```

**Comment by shadowfacts** [comment]
Problem with Witchery.
