### ISSUE TITLE
NPE when scanning placed creeper head block

### ISSUE THREAD

**Issue by TheNumenorean** [simeonradivoev/MatterOverdrive#438]
```
java.lang.NullPointerException: Ticking entity
	at net.minecraft.item.ItemStack.func_77960_j(ItemStack.java:217)
	at matteroverdrive.data.ItemPattern.<init>(ItemPattern.java:29)
	at matteroverdrive.data.ItemPattern.<init>(ItemPattern.java:25)
	at matteroverdrive.items.MatterScanner.setSelected(MatterScanner.java:239)
	at matteroverdrive.items.MatterScanner.onUsingTick(MatterScanner.java:432)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234)
	at net.minecraft.client.entity.EntityClientPlayerMP.func_70071_h_(SourceFile:63)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.World.func_72870_g(World.java:2034)
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2006)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by shadowfacts** [comment]
Fixed in cdb57fd74822c5e0d58b9950ef537e32e672ccdb.
