### ISSUE TITLE
Crash when opening GUI on matter scanner (C button)

### ISSUE THREAD

**Issue by viper2g1** [simeonradivoev/MatterOverdrive#445]
Here is my crash report: 

Edit: Using the latest dev build available (MatterOverdrive-1.7.10-0.4.1-build-18.jar)

http://pastebin.com/3Ujpytnv

**Comment by viper2g1** [comment]
Here is another crash I got today when trying to use the Matter Scanner GUI:

    [08:40:36] [Client thread/INFO] [inventorytweaks/]: matteroverdrive.gui.GuiMatterScanner
    [08:40:36] [Client thread/INFO] [inventorytweaks/]: matteroverdrive.container.ContainerFalse
    [08:40:36] [Client thread/ERROR] [FML/]: There was a critical exception handling a packet on channel mo_channel
    io.netty.handler.codec.EncoderException: java.lang.NullPointerException
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107) ~[MessageToMessageEncoder.class:?]
	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[MessageToMessageCodec.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:688) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:717) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:893) ~[DefaultChannelPipeline.class:?]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:239) ~[AbstractChannel.class:?]
	at cpw.mods.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendToServer(SimpleNetworkWrapper.java:236) ~[SimpleNetworkWrapper.class:?]
	at matteroverdrive.network.PacketPipeline.sendToServer(PacketPipeline.java:132) ~[PacketPipeline.class:?]
	at matteroverdrive.gui.GuiMatterScanner.<init>(GuiMatterScanner.java:63) ~[GuiMatterScanner.class:?]
	at matteroverdrive.items.MatterScanner.DisplayGuiScreen(MatterScanner.java:296) ~[MatterScanner.class:?]
	at matteroverdrive.handler.KeyHandler.onKeyInput(KeyHandler.java:74) ~[KeyHandler.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_316_KeyHandler_onKeyInput_KeyInputEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:?]
	at cpw.mods.fml.common.FMLCommonHandler.fireKeyInput(FMLCommonHandler.java:540) ~[FMLCommonHandler.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1873) [bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_66]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
    
    Caused by: java.lang.NullPointerException
	at matteroverdrive.network.packet.bi.PacketMatterScannerGetDatabase.toBytes(PacketMatterScannerGetDatabase.java:70) ~[PacketMatterScannerGetDatabase.class:?]
	at cpw.mods.fml.common.network.simpleimpl.SimpleIndexedCodec.encodeInto(SimpleIndexedCodec.java:11) ~[SimpleIndexedCodec.class:?]
	at cpw.mods.fml.common.network.simpleimpl.SimpleIndexedCodec.encodeInto(SimpleIndexedCodec.java:7) ~[SimpleIndexedCodec.class:?]
	at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.encode(FMLIndexedMessageToMessageCodec.java:51) ~[FMLIndexedMessageToMessageCodec.class:?]
	at io.netty.handler.codec.MessageToMessageCodec$1.encode(MessageToMessageCodec.java:67) ~[MessageToMessageCodec$1.class:?]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:89) ~[MessageToMessageEncoder.class:?]
	... 26 more

**Comment by KILLAKAN10** [comment]
Same Problem here, theres also a crash after accessing pattern monitor after scanner gui
http://pastebin.com/zNctaLhi
 and just my luck, firing a left-click reactive weapon,
http://pastebin.com/BpUhQkzS
 I am also finding problems with the creative storage drive.
http://pastebin.com/52jpWgdV

**Comment by shadowfacts** [comment]
See #482
