### ISSUE TITLE
Mod won't load?

### ISSUE THREAD

**Issue by StreamGamer** [simeonradivoev/MatterOverdrive#468]
Brief explanation of problem: Whenever I try to open MC with Matter Overdrive (note: i'm using other mods), It crashes.

Steps to reproduce:

Crash report paste (if any) on [gist](gist.github.com): Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: matteroverdrive/entity/AndroidPlayer
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:162)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:515)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:239)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
Theres the first chunk of it. I think it's something to do with a thing called Android Player...
MatterOverdrive version: MatterOverdrive-1.7.10-0.4.0 - Stable Mining

Minecraft version: 1.7.10

**Comment by shadowfacts** [comment]
CoFH core is required before 0.4.1
