### ISSUE TITLE
Entity Already Registered: Latest Version

### ISSUE THREAD

**Issue by GoldyManser** [simeonradivoev/MatterOverdrive#502]
Brief explanation of problem: While starting my game, i encounter this entity already registered error, not sure if this is Matter Overdrives fault, but i can't seem to change this in the config.

Steps to reproduce: Start the game

Crash report paste (if any) on [gist](gist.github.com): 
```
[B#347]  java.lang.IllegalArgumentException: ID is already registered: 176
[B#347]  	at net.minecraft.entity.EntityList.func_75618_a(EntityList.java:94)
[B#347]  	at cpw.mods.fml.common.registry.EntityRegistry.registerGlobalEntityID(EntityRegistry.java:199)
[B#347]  	at matteroverdrive.init.MatterOverdriveEntities.addEntity(MatterOverdriveEntities.java:78)
[B#347]  	at matteroverdrive.init.MatterOverdriveEntities.register(MatterOverdriveEntities.java:60)
[B#347]  	at matteroverdrive.MatterOverdrive.postInit(MatterOverdrive.java:166)
[B#347]  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[B#347]  	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[B#347]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[B#347]  	at java.lang.reflect.Method.invoke(Unknown Source)
[B#347]  	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
[B#347]  	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
[B#347]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[B#347]  	at java.lang.reflect.Method.invoke(Unknown Source)
[B#347]  	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[B#347]  	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[B#347]  	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[B#347]  	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[B#347]  	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[B#347]  	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
[B#347]  	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
[B#347]  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[B#347]  	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[B#347]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[B#347]  	at java.lang.reflect.Method.invoke(Unknown Source)
[B#347]  	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[B#347]  	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[B#347]  	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[B#347]  	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[B#347]  	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[B#347]  	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
[B#347]  	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:742)
[B#347]  	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
[B#347]  	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
[B#347]  	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
[B#347]  	at net.minecraft.client.main.Main.main(SourceFile:148)
[B#347]  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[B#347]  	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[B#347]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[B#347]  	at java.lang.reflect.Method.invoke(Unknown Source)
[B#347]  	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[B#347]  	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

MatterOverdrive version: 0.4.1

Minecraft version: 1.7.10 modded w/forge

**Comment by Lazarix** [comment]
Search your entire config folder for '176' using grep or find if you are on Linux. Two of your configs are trying to use block ID 176.

**Comment by GoldyManser** [comment]
How would i go about this on windows?

**Comment by Lazarix** [comment]
A simple way is using a utility to do it for you. Wingrep works:
http://www.wingrep.com/

**Comment by shadowfacts** [comment]
No longer applicable as global entities IDs are now used.
