### ISSUE TITLE
server ticking for analizer

### ISSUE THREAD

**Issue by plenet10** [simeonradivoev/MatterOverdrive#516]
Brief explanation of problem: The server gives a TileEntity error on The Matter Analyzer Machine
Don't konw if its fixable 

Thanks for your efford

Steps to reproduce: Just playing don't know exactly i got here. 

Crash report paste (if any) on [gist](gist.github.com):[Server thread/FATAL] [Matter Overdrive]: There was a problem while ticking MatterNetworkHandler matteroverdrive.machines.analyzer.TileEntityMachineMatterAnalyzer@6a5eb1e2
java.lang.NullPointerException

MatterOverdrive version:0.4.1

Minecraft version:1.7.10

**Comment by shadowfacts** [comment]
Post the entire crash log.

**Comment by plenet10** [comment]
this is all i have if you need other thing just say it and i will try to provide
[fml-server-latest.zip](https://github.com/simeonradivoev/MatterOverdrive/files/279643/fml-server-latest.zip)

**Comment by alicheek** [comment]
yes i can confirm this also we have it happening on our server too  on version 0.4.1 as @plenet10 states there is no crash reports nor extra information to go on but thought i would just back up whats been said

**Comment by alicheek** [comment]
oh got more info now : 

[15:15:55 FATAL]: There was a problem while ticking MatterNetworkHandler matteroverdrive.machines.analyzer.TileEntityMachineMatterAnalyzer@fff78ae3
java.lang.NullPointerException
        at matteroverdrive.data.ItemPattern.<init>(ItemPattern.java:29) ~[ItemPattern.class:?]
        at matteroverdrive.data.ItemPattern.<init>(ItemPattern.java:25) ~[ItemPattern.class:?]
        at matteroverdrive.machines.analyzer.components.MatterNetworkComponentAnalyzer.manageValidDestinationCheck(MatterNetworkComponentAnalyzer.java:154) ~[MatterNetworkComponentAnalyzer.class:?]
        at matteroverdrive.machines.analyzer.components.MatterNetworkComponentAnalyzer.onNetworkTick(MatterNetworkComponentAnalyzer.java:109) ~[MatterNetworkComponentAnalyzer.class:?]
        at matteroverdrive.machines.analyzer.TileEntityMachineMatterAnalyzer.onNetworkTick(TileEntityMachineMatterAnalyzer.java:295) ~[TileEntityMachineMatterAnalyzer.class:?]
        at matteroverdrive.handler.MatterNetworkTickHandler.updateHandler(MatterNetworkTickHandler.java:45) [MatterNetworkTickHandler.class:?]
        at matteroverdrive.handler.TickHandler.onWorldTick(TickHandler.java:110) [TickHandler.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_525_TickHandler_onWorldTick_WorldTickEvent.invoke(.dynamic) [?:1.7.10-1614.58]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) [ASMEventHandler.class:1.7.10-1614.58]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:1.7.10-1614.58]
        at cpw.mods.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:273) [FMLCommonHandler.class:1.7.10-1614.58]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:957) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]

**Comment by alicheek** [comment]
Ive put it in a pastebin link so its a bit easier to read. 

http://pastebin.com/r7kmtAMQ

**Comment by alicheek** [comment]
@shadowfacts  any updates ? :)
