### ISSUE TITLE
Custom world generator crashes when trying to generate a village

### ISSUE THREAD

**Issue by roboderpy** [simeonradivoev/MatterOverdrive#567]
```
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at rtg.event.EventManagerRTG.onGetVillageBlockID(EventManagerRTG.java:193)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_337_EventManagerRTG_onGetVillageBlockID_GetVillageBlockID.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraft.world.gen.structure.StructureVillagePieces$Village.func_151558_b(StructureVillagePieces.java:1630)
	at net.minecraft.world.gen.structure.StructureVillagePieces$Village.func_151549_a(StructureVillagePieces.java:1703)
	at net.minecraft.world.gen.structure.StructureVillagePieces$Well.func_74875_a(StructureVillagePieces.java:1762)
	at net.minecraft.world.gen.structure.StructureStart.func_75068_a(StructureStart.java:44)
	at net.minecraft.world.gen.structure.MapGenStructure.func_75051_a(MapGenStructure.java:93)
	at com.xcompwiz.mystcraft.symbol.symbols.SymbolVillages$Populator.populate(SymbolVillages.java:42)
	at com.xcompwiz.mystcraft.world.AgeController.populate(AgeController.java:572)
	at com.xcompwiz.mystcraft.world.ChunkProviderMyst.func_73153_a(ChunkProviderMyst.java:169)
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:279)
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1055)
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190)
	at com.xcompwiz.mystcraft.world.profiling.WorldProviderMystDummy$ChunkProviderServerDummy.originalLoadChunk(WorldProviderMystDummy.java:62)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
	at com.xcompwiz.mystcraft.world.profiling.WorldProviderMystDummy.generateNextChunk(WorldProviderMystDummy.java:217)
	at com.xcompwiz.mystcraft.world.profiling.InstabilityDataCalculator.stepChunkGeneration(InstabilityDataCalculator.java:343)
	at com.xcompwiz.mystcraft.world.profiling.InstabilityDataCalculator.onServerTick(InstabilityDataCalculator.java:180)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_559_InstabilityDataCalculator_onServerTick_ServerTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:247)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:590)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

After that crash, unable to load world until Metter Overdrive is removed.

**Comment by shadowfacts** [comment]
1. That crash is either caused by MystCraft or Realistic Terrain Generation, no Matter Overdrive.
2. 1.7.10 is no longer supported.

**Comment by roboderpy** [comment]
Look at title closely
```Custom world generator crashes```
It is caused when custom world generator calls your mod class and it throws exception

**Comment by shadowfacts** [comment]
If Matter Overdrive was crashing, it would be in the stack trace. RTG is crashing because it's trying to do something invalid.

Additionally, RTG has undergone major changes. In the [1.7.10 branch](https://github.com/Team-RTG/Realistic-Terrain-Generation/tree/1.7.10-dev) of RTG, the `onGetVillageBlockID` method no longer exists in the class given in the stack trace.
