### ISSUE TITLE
Severs goes instantly offline

### ISSUE THREAD

**Issue by henry979** [simeonradivoev/MatterOverdrive#594]
Server just instantly goes offline please help

**Comment by Muirrum** [comment]
What server?
What MC Version?
What Mod Version?

**Comment by shadowfacts** [comment]
Post the `fml-server-latest.log` file using [Gist](https://gist.github.com).

**Comment by henry979** [comment]
a cauldron server
1.7.10
0.4.1

**Comment by shadowfacts** [comment]
1. You still haven't posted the log
2. Try on normal Forge instead of Cauldron

**Comment by henry979** [comment]
```
---- Minecraft Crash Report ----
// Why did you do that?

Time: 10/21/16 10:17 PM
Description: Exception in server tick loop

cpw.mods.fml.common.LoaderException: java.lang.ClassNotFoundException:
matteroverdrive.MatterOverdrive
 at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
 at cpw.mods.fml.common.Loader.loadMods(Loader.java:522)
 at
cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:87)
 at
cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:318)
 at
net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:176)
 at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:620)
 at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: matteroverdrive.MatterOverdrive
 at
net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
 at java.lang.ClassLoader.loadClass(Unknown Source)
 at java.lang.ClassLoader.loadClass(Unknown Source)
 at cpw.mods.fml.common.ModClassLoader.loadClass(ModClassLoader.java:58)
 at java.lang.Class.forName0(Native Method)
 at java.lang.Class.forName(Unknown Source)
 at
cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:440)
 at sun.reflect.GeneratedMethodAccessor32.invoke(Unknown Source)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
 at java.lang.reflect.Method.invoke(Unknown Source)
 at
com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
 at
com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
 at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
 at
com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
 at com.google.common.eventbus.EventBus.post(EventBus.java:275)
 at
cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
 at
cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
 at java.lang.reflect.Method.invoke(Unknown Source)
 at
com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
 at
com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
 at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
 at
com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
 at com.google.common.eventbus.EventBus.post(EventBus.java:275)
 at
cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
 at cpw.mods.fml.common.Loader.loadMods(Loader.java:511)
 ... 5 more
Caused by: java.lang.UnsupportedClassVersionError:
matteroverdrive/MatterOverdrive : Unsupported major.minor version 52.0
 at java.lang.ClassLoader.defineClass1(Native Method)
 at java.lang.ClassLoader.defineClass(Unknown Source)
 at java.security.SecureClassLoader.defineClass(Unknown Source)
 at
net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
 ... 32 more


A detailed walkthrough of the error, its code path and all known details is
as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
 Minecraft Version: 1.7.10
 Operating System: Linux (amd64) version 3.10.0-327.4.5.el7.x86_64
 Java Version: 1.7.0_80, Oracle Corporation
 Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle
Corporation
 Memory: 51779856 bytes (49 MB) / 259588096 bytes (247 MB) up to 4151836672
bytes (3959 MB)
 JVM Flags: 8 total; -Xms256M -Xmx4096M -XX:MaxPermSize=256M
-XX:+UseParNewGC -XX:+CMSIncrementalPacing -XX:+CMSClassUnloadingEnabled
-XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10
 AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
 IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
 FML: MCP v9.05 FML v7.10.114.1388 Minecraft Forge 10.13.3.1403 34 mods
loaded, 34 mods active
 mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed
 FML{7.10.114.1388} [Forge Mod Loader] (cauldron.jar) Unloaded->Constructed
 Forge{10.13.3.1403} [Minecraft Forge] (cauldron.jar) Unloaded->Constructed
 AM2-Preloader{0.0.3} [AMCore] (minecraft.jar) Unloaded->Constructed
 CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar)
Unloaded->Constructed
 WarpDriveCore{1.7.10-1.3.22.-} [WarpDriveCore] (minecraft.jar)
Unloaded->Constructed
 dynamicswordskills{1.7.10-1.7} [Dynamic Sword Skills]
(1.7.10-dynamicswordskills-1.7.jar) Unloaded->Constructed
 AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4.jar)
Unloaded->Constructed
 arsmagica2{1.4.0.009} [Ars Magica 2] (1.7.10_AM2-1.4.0.009.jar)
Unloaded->Constructed
 lightsabers{1.7.10} [Advanced Lightsabers Mod]
(AdvancedLightsabers-1.7.10-1.0.4.jar) Unloaded->Constructed
 AgriCraft{1.7.10-1.5.0} [AgriCraft] (AgriCraft-1.7.10-1.5.0.jar)
Unloaded->Constructed
 armourersWorkshop{1.7.10-0.42.2} [Armourer's Workshop]
(Armourers-Workshop-1.7.10-0.42.2.jar) Unloaded->Constructed
 plushieWrapper{0.0.0} [Plushie Wrapper]
(Armourers-Workshop-1.7.10-0.42.2.jar) Unloaded->Constructed
 Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar)
Unloaded->Constructed
 BuildCraft|Core{7.1.17} [BuildCraft] (buildcraft-7.1.17.jar)
Unloaded->Constructed
 BuildCraft|Silicon{7.1.17} [BC Silicon] (buildcraft-7.1.17.jar)
Unloaded->Constructed
 BuildCraft|Transport{7.1.17} [BC Transport] (buildcraft-7.1.17.jar)
Unloaded->Constructed
 BuildCraft|Builders{7.1.17} [BC Builders] (buildcraft-7.1.17.jar)
Unloaded->Constructed
 BuildCraft|Energy{7.1.17} [BC Energy] (buildcraft-7.1.17.jar)
Unloaded->Constructed
 BuildCraft|Robotics{7.1.17} [BC Robotics] (buildcraft-7.1.17.jar)
Unloaded->Constructed
 BuildCraft|Factory{7.1.17} [BC Factory] (buildcraft-7.1.17.jar)
Unloaded->Constructed
 ComputerCraft{1.75} [ComputerCraft] (ComputerCraft1.75.jar)
Unloaded->Constructed
 customnpcs{1.7.10d} [CustomNpcs] (CustomNPCs_1.7.10d(21feb16).jar)
Unloaded->Constructed
 fastleafdecay{1.3} [Fast Leaf Decay] (FastLeafDecay-Mod-1.7.10.jar)
Unloaded->Constructed
 IC2{2.2.791-experimental} [IndustrialCraft 2]
(Industrial-Craft-2-Mod-Experimental-1.7.10.jar) Unloaded->Constructed
 IC2NuclearControl{2.4.1a} [Nuclear Control 2]
(IC2NuclearControl-2.4.1a.jar) Unloaded->Constructed
 LogisticsPipes{0.9.3.99} [Logistics Pipes] (logisticspipes-0.9.3.99.jar)
Unloaded->Constructed
 mo{0.4.1} [Matter Overdrive] (MatterOverdrive-1.7.10-0.4.1.jar)
Unloaded->Errored
 ForgeMultipart{1.1.2.331} [Forge Multipart]
(ForgeMultipart-1.7.10-1.1.2.331-universal.jar) Unloaded->Constructed
 Mekanism{9.1.0} [Mekanism] (Mekanism-1.7.10-9.1.0.281.jar)
Unloaded->Constructed
 PowerConverters3{1.7.10-2.11} [Power Converters 3]
(PowerConverters-1.7.10-2.11.jar) Unloaded->Constructed
 WarpDrive{1.7.10-1.3.22.-} [WarpDrive] (WarpDrive-1.7.10-1.3.22.-.jar)
Unloaded->Constructed
 McMultipart{1.1.2.331} [Minecraft Multipart Plugin]
(ForgeMultipart-1.7.10-1.1.2.331-universal.jar) Unloaded->Constructed
 ForgeMicroblock{1.1.2.331} [Forge Microblocks]
(ForgeMultipart-1.7.10-1.1.2.331-universal.jar) Unloaded->Constructed
 Profiler Position: N/A (disabled)
 Is Modded: Definitely; Server brand changed to
'cauldron,craftbukkit,mcpc,fml,forge'
 Type: Dedicated Server (map_server.txt)
```

**Comment by shadowfacts** [comment]
Java 8 is required.
