### ISSUE TITLE
1.9.4 build (sniper problems)

### ISSUE THREAD

**Issue by aiRobot13** [simeonradivoev/MatterOverdrive#597]
Hello there, just tested a build and then, minecraft crash attack happend
how to proceed put an ion sniper rifle in the weapon station, then add scope,(poof)

```
Time: 2016-11-02 23:02
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at matteroverdrive.client.render.weapons.modules.ModuleSniperScopeRender.renderModule(ModuleSniperScopeRender.java:46)
	at matteroverdrive.client.render.weapons.WeaponRenderHandler.renderModules(WeaponRenderHandler.java:237)
	at matteroverdrive.client.render.weapons.WeaponRenderHandler.renderWeaponAndModules(WeaponRenderHandler.java:163)
	at matteroverdrive.gui.GuiWeaponStation.func_146976_a(GuiWeaponStation.java:165)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:76)
	at matteroverdrive.gui.MOGuiBase.func_73863_a(MOGuiBase.java:136)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:355)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1095)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1077)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:369)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at matteroverdrive.client.render.weapons.modules.ModuleSniperScopeRender.renderModule(ModuleSniperScopeRender.java:46)
	at matteroverdrive.client.render.weapons.WeaponRenderHandler.renderModules(WeaponRenderHandler.java:237)
	at matteroverdrive.client.render.weapons.WeaponRenderHandler.renderWeaponAndModules(WeaponRenderHandler.java:163)
	at matteroverdrive.gui.GuiWeaponStation.func_146976_a(GuiWeaponStation.java:165)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:76)
	at matteroverdrive.gui.MOGuiBase.func_73863_a(MOGuiBase.java:136)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:355)

-- Screen render details --
Details:
	Screen name: matteroverdrive.gui.GuiWeaponStation
	Mouse location: Scaled: (276, 64). Absolute: (1105, 820)
	Screen size: Scaled: (480, 270). Absolute: (1920, 1080). Scale factor of 4

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Pumpemperor'/1121, l='MpServer', x=-166,69, y=64,00, z=8,31]]
	Chunk stats: MultiplayerChunkCache: 1118, 1118
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-157,64,21), Chunk: (at 3,4,5 in -10,1; contains blocks -160,0,16 to -145,255,31), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 11225 game time, 28212 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 81 total; [EntitySkeleton['Skeleton'/16406, l='MpServer', x=-168,50, y=17,00, z=55,50], EntityPig['Pig'/57, l='MpServer', x=-228,30, y=64,00, z=5,60], EntityPig['Pig'/58, l='MpServer', x=-215,69, y=63,00, z=12,27], EntityPig['Pig'/59, l='MpServer', x=-217,83, y=66,00, z=-1,20], EntityPig['Pig'/60, l='MpServer', x=-224,71, y=64,00, z=6,00], EntityPig['Pig'/61, l='MpServer', x=-223,26, y=64,00, z=34,20], EntityPig['Pig'/62, l='MpServer', x=-225,49, y=63,00, z=28,68], EntityPig['Pig'/63, l='MpServer', x=-218,79, y=63,00, z=37,49], EntityPig['Pig'/64, l='MpServer', x=-215,66, y=63,00, z=24,78], EntityPig['Pig'/88, l='MpServer', x=-202,50, y=63,00, z=53,50], EntityPig['Pig'/89, l='MpServer', x=-202,50, y=63,00, z=53,50], EntityPig['Pig'/90, l='MpServer', x=-202,50, y=63,00, z=54,50], EntityPig['Pig'/91, l='MpServer', x=-203,50, y=63,00, z=54,50], EntityPig['Pig'/102, l='MpServer', x=-146,73, y=64,00, z=31,15], EntityPig['Pig'/103, l='MpServer', x=-200,34, y=63,00, z=11,78], EntityPig['Pig'/104, l='MpServer', x=-199,34, y=63,00, z=28,23], EntityPig['Pig'/108, l='MpServer', x=-155,45, y=62,00, z=54,55], EntityPig['Pig'/109, l='MpServer', x=-117,79, y=62,34, z=14,26], EntityPig['Pig'/110, l='MpServer', x=-168,47, y=63,00, z=58,33], EntityPig['Pig'/111, l='MpServer', x=-185,21, y=63,00, z=37,34], EntityPig['Pig'/112, l='MpServer', x=-177,26, y=63,00, z=48,28], EntityPig['Pig'/113, l='MpServer', x=-176,20, y=63,00, z=55,24], EntityPig['Pig'/114, l='MpServer', x=-181,28, y=63,00, z=46,37], EntityPig['Pig'/115, l='MpServer', x=-186,45, y=63,00, z=46,24], EntitySkeleton['Skeleton'/16509, l='MpServer', x=-130,50, y=46,00, z=84,50], EntityCow['Cow'/128, l='MpServer', x=-156,50, y=65,00, z=-57,50], EntityCow['Cow'/129, l='MpServer', x=-152,50, y=64,00, z=-58,50], EntityCow['Cow'/130, l='MpServer', x=-155,50, y=68,00, z=-58,50], EntityCow['Cow'/131, l='MpServer', x=-152,50, y=66,00, z=-60,50], EntityBat['Bat'/16519, l='MpServer', x=-176,26, y=42,38, z=86,13], EntitySheep['Sheep'/139, l='MpServer', x=-92,50, y=64,00, z=-15,50], EntitySheep['Sheep'/140, l='MpServer', x=-93,50, y=63,00, z=-14,50], EntitySheep['Sheep'/141, l='MpServer', x=-93,50, y=64,00, z=-18,50], EntitySheep['Sheep'/142, l='MpServer', x=-97,50, y=64,00, z=-16,50], EntityItem['item.item.porkchopRaw'/16589, l='MpServer', x=-204,32, y=63,00, z=18,70], EntityXPOrb['Experience Orb'/16624, l='MpServer', x=-208,45, y=63,00, z=17,89], EntityZombie['Zombie'/16630, l='MpServer', x=-151,50, y=24,00, z=66,50], EntityZombie['Zombie'/16724, l='MpServer', x=-190,50, y=34,00, z=11,50], EntityBat['Bat'/16782, l='MpServer', x=-136,04, y=12,89, z=-33,86], EntityCreeper['Creeper'/16869, l='MpServer', x=-200,50, y=32,00, z=52,50], EntityWitch['Witch'/16915, l='MpServer', x=-165,50, y=52,00, z=48,50], EntityCreeper['Creeper'/16978, l='MpServer', x=-156,50, y=32,00, z=77,50], EntityZombie['Zombie'/17025, l='MpServer', x=-149,50, y=30,00, z=-65,50], EntityCreeper['Creeper'/17173, l='MpServer', x=-155,50, y=25,00, z=48,50], EntityCreeper['Creeper'/17228, l='MpServer', x=-224,50, y=13,00, z=14,50], EntityCreeper['Creeper'/17388, l='MpServer', x=-119,50, y=43,00, z=81,50], EntitySkeleton['Skeleton'/17400, l='MpServer', x=-108,50, y=50,00, z=28,50], EntityZombie['Zombie'/17475, l='MpServer', x=-147,50, y=27,00, z=63,50], EntityBat['Bat'/17509, l='MpServer', x=-186,75, y=31,01, z=57,25], EntitySkeleton['Skeleton'/17556, l='MpServer', x=-211,50, y=42,00, z=35,50], EntitySpider['Spider'/17626, l='MpServer', x=-167,21, y=52,00, z=50,70], EntitySkeleton['Skeleton'/17646, l='MpServer', x=-176,50, y=35,00, z=16,50], EntityZombie['Zombie'/17675, l='MpServer', x=-133,50, y=21,00, z=-29,50], EntitySkeleton['Skeleton'/17785, l='MpServer', x=-223,50, y=13,00, z=17,50], EntityCreeper['Creeper'/17820, l='MpServer', x=-221,50, y=41,00, z=18,50], EntityCreeper['Creeper'/17836, l='MpServer', x=-127,50, y=27,00, z=17,50], EntityZombie['Zombie'/17837, l='MpServer', x=-161,50, y=34,00, z=78,50], EntityZombie['Zombie'/17909, l='MpServer', x=-132,80, y=31,00, z=68,49], EntityBat['Bat'/17915, l='MpServer', x=-131,49, y=26,40, z=64,63], EntityBat['Bat'/17929, l='MpServer', x=-146,12, y=23,12, z=55,38], EntityZombie['Zombie'/17935, l='MpServer', x=-118,50, y=46,00, z=42,50], EntityZombie['Zombie'/17978, l='MpServer', x=-182,50, y=34,00, z=13,50], EntityBat['Bat'/18009, l='MpServer', x=-204,74, y=34,67, z=48,88], EntitySkeleton['Skeleton'/18054, l='MpServer', x=-239,50, y=44,00, z=22,50], EntityZombie['Zombie'/18055, l='MpServer', x=-124,50, y=50,00, z=50,50], EntityBat['Bat'/18075, l='MpServer', x=-160,70, y=26,53, z=47,85], EntityBat['Bat'/18076, l='MpServer', x=-139,13, y=50,66, z=67,60], EntityPlayerSP['Pumpemperor'/1121, l='MpServer', x=-165,81, y=64,00, z=4,45], EntityZombie['Zombie'/14404, l='MpServer', x=-142,50, y=21,00, z=-31,50], EntityBat['Bat'/14559, l='MpServer', x=-182,50, y=34,46, z=12,26], EntityCreeper['Creeper'/14664, l='MpServer', x=-115,50, y=26,00, z=36,50], EntityPlayerSP['Pumpemperor'/1121, l='MpServer', x=-166,69, y=64,00, z=8,31], EntityBat['Bat'/15042, l='MpServer', x=-190,53, y=52,18, z=1,70], EntityZombie['Zombie'/15485, l='MpServer', x=-145,50, y=53,00, z=45,50], EntitySkeleton['Skeleton'/15634, l='MpServer', x=-152,50, y=38,00, z=-54,50], EntityCreeper['Creeper'/15837, l='MpServer', x=-163,50, y=45,00, z=48,50], EntitySkeleton['Skeleton'/15890, l='MpServer', x=-233,50, y=18,00, z=-35,50], EntityZombie['Zombie'/16140, l='MpServer', x=-141,50, y=30,00, z=66,50], EntitySpider['Spider'/16251, l='MpServer', x=-211,50, y=42,00, z=34,50], EntityCreeper['Creeper'/16334, l='MpServer', x=-142,44, y=49,00, z=56,80], EntitySkeleton['Skeleton'/16359, l='MpServer', x=-186,50, y=30,00, z=49,50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:412)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2651)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:390)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.9.4
	Operating System: Mac OS X (x86_64) version 10.12
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 350873856 bytes (334 MB) / 961839104 bytes (917 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 5 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.28 Powered by Forge 12.17.0.2051 4 mods loaded, 4 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.9.4-12.17.0.2051.jar) 
	UCHIJAAAA	Forge{12.17.0.2051} [Minecraft Forge] (forge-1.9.4-12.17.0.2051.jar) 
	UCHIJAAAA	mo{0.4.3} [Matter Overdrive] (MatterOverdrive-1.9.4-0.4.4-build-55.jar) 
	Loaded coremods (and transformers): 
	Launched Version: 1.9.4-forge1.9.4-12.17.0.2051
	LWJGL: 2.9.2
	OpenGL: Intel HD Graphics 5000 OpenGL Engine GL version 2.1 INTEL-10.18.65, Intel Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (UK)
	Profiler Position: N/A (disabled)
	CPU: net.minecraft.client.Minecraft$15@2a162006
```

**Comment by Muirrum** [comment]
@shadowfacts Testing now

**Comment by Muirrum** [comment]
@shadowfacts Bug confirmed.
Logs: https://hastebin.com/ahorinelut.pas
