### ISSUE TITLE
gravitational_stabilizer crashed game when tried to put facing up, see crash report..

### ISSUE THREAD

**Issue by jonabrv1965** [simeonradivoev/MatterOverdrive#640]
MatterOverdrive-1.10.2-0.5.1

---- Minecraft Crash Report ----

WARNING: coremods are present:
  MovingWorldCoreMod (movingworld-1.10.2-0007-full.jar)
  ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.7.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.65-beta.jar)
  NWRTweak (redstonepaste-mc1.9.4-1.7.4.jar)
  BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.3.338.jar)
  llibrary (llibrary-1.7.4-1.10.2.jar)
  AdvancedRocketryPlugin (AdvancedRocketry-1.10.2-1.0.12.jar)
  mysttmtgravitymod (UpAndDownAndAllAround-2.6.jar)
  BCModPlugin (zz-backpacks 1.10.2 - 3.1.5.jar)
Contact their authors BEFORE contacting forge

// I feel sad now :(

Time: 3/12/17 10:28 PM
Description: Unexpected error

java.lang.IllegalArgumentException: Cannot set property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[north, south, west, east]} to up on block mo:gravitational_stabilizer, it is not an allowed value
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177226_a(BlockStateContainer.java:229)
	at matteroverdrive.blocks.BlockGravitationalStabilizer.func_180633_a(BlockGravitationalStabilizer.java:98)
	at net.minecraft.item.ItemBlock.placeBlockAt(ItemBlock.java:171)

**Comment by jonabrv1965** [comment]
Hi Shadow, thank you for the "speed"!!, I can confirm that this orientation issue appears with the reactor controller also
