### ISSUE TITLE
A bucket crash....

### ISSUE THREAD

**Issue by jonabrv1965** [simeonradivoev/MatterOverdrive#642]
When trying to right-click a water/lava bucket in air (it does not happen if right-clicked to any block, just with air) I got the following crash (MatterOverdrive-1.10.2-0.5.1) :

---- Minecraft Crash Report ----

WARNING: coremods are present:
  MovingWorldCoreMod (movingworld-1.10.2-0007-full.jar)
  ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.7.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.65-beta.jar)
  NWRTweak (redstonepaste-mc1.9.4-1.7.4.jar)
  BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.3.338.jar)
  llibrary (llibrary-1.7.4-1.10.2.jar)
  AdvancedRocketryPlugin (AdvancedRocketry-1.10.2-1.0.12.jar)
  mysttmtgravitymod (UpAndDownAndAllAround-2.6.jar)
  BCModPlugin (zz-backpacks 1.10.2 - 3.1.5.jar)
Contact their authors BEFORE contacting forge

// You're mean.

Time: 3/13/17 7:44 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at matteroverdrive.handler.BucketHandler.onBucketFill(BucketHandler.java:46)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_212_BucketHandler_onBucketFill_FillBucketEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.event.ForgeEventFactory.onBucketUse(ForgeEventFactory.java:366)
	at net.minecraft.item.ItemBucket.func_77659_a(ItemBucket.java:40)
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:162)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187101_a(PlayerControllerMP.java:495)
	at PlayerControllerOF.func_187101_a(PlayerControllerOF.java:73)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1544)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2184)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1961)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1749)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by shadowfacts** [comment]
Already fixed in 21ab4b8fad2f2fceee38c32874992bafcae68370.
