### ISSUE TITLE
Random Crash while game play when someone eats something (near)

### ISSUE THREAD

**Issue by Tempest2113** [simeonradivoev/MatterOverdrive#657]
When someone eats something everyone else near the person gets a white screen and get 
this error:

Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at matteroverdrive.client.render.RenderWeaponsBeam.shouldRenderBeam(RenderWeaponsBeam.java:157)
	at matteroverdrive.client.render.RenderWeaponsBeam.lambda$renderOthers$2(RenderWeaponsBeam.java:88)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.forEach(Unknown Source)
	at matteroverdrive.client.render.RenderWeaponsBeam.renderOthers(RenderWeaponsBeam.java:86)
	at matteroverdrive.client.render.RenderWeaponsBeam.onRenderWorldLast(RenderWeaponsBeam.java:72)
	at matteroverdrive.client.RenderHandler.onRenderWorldLast(RenderHandler.java:270)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_773_RenderHandler_onRenderWorldLast_RenderWorldLastEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:166)
	at sun.reflect.GeneratedMethodAccessor78.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at Reflector.callVoid(Reflector.java:512)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1888)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1566)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1345)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

This happened 10 times in 2hours

**Comment by LunarW15** [comment]
Same issue

**Comment by shadowfacts** [comment]
Already fixed in c37e6cbfa7e2a126c20222a81f8f85f49ed7e5c6.
