### ISSUE TITLE
[1.10.2][0.5.1] Fusion Reactor Crash

### ISSUE THREAD

**Issue by codetaylor** [simeonradivoev/MatterOverdrive#690]
```
Time: 5/14/17 3:13 PM
Description: Ticking block entity

java.lang.AbstractMethodError: matteroverdrive.tile.TileEntityFusionReactorPart.isInvalid()Z
	at matteroverdrive.multiblock.MultiBlockTileStructureMachine.update(MultiBlockTileStructureMachine.java:57)
	at matteroverdrive.machines.fusionReactorController.TileEntityMachineFusionReactorController.manageStructure(TileEntityMachineFusionReactorController.java:230)
	at matteroverdrive.machines.fusionReactorController.TileEntityMachineFusionReactorController.func_73660_a(TileEntityMachineFusionReactorController.java:152)
	at net.minecraft.world.World.func_72939_s(World.java:1804)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)
```

I looked and I'm pretty sure that this is happening because the class [TileEntityFusionReactorPart](https://github.com/simeonradivoev/MatterOverdrive/blob/1.10.2/src/main/java/matteroverdrive/tile/TileEntityFusionReactorPart.java) implements the interface [IMultiBlockTile](https://github.com/simeonradivoev/MatterOverdrive/blob/1.10.2/src/main/java/matteroverdrive/multiblock/IMultiBlockTile.java) but does not implement the interface's method `isInvalid()`.

According to AbstractMethodError JavaDoc:

> Normally, this error is caught by the compiler; this error can only occur at run time if the definition of some class has incompatibly changed since the currently executing method was last compiled.

Hope this helps! :)

**Comment by Muirrum** [comment]
Can I please have the entire crash report?

**Comment by Muirrum** [comment]
Closing due to lack of information and response.
