### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Extrallian** [simeonradivoev/MatterOverdrive#697]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MicdoodlePlugin (MicdoodleCore-1.10.2-4.0.0.107.jar)
  ForgelinPlugin (Forgelin-1.5.0.jar)
  ChiselCorePlugin (Chisel-MC1.10.2-0.0.10.22.jar)
Contact their authors BEFORE contacting forge

// There are four lights!

Time: 6/13/17 10:47 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Matter Overdrive (mo)
Caused by: net.minecraft.util.ReportedException: Generating mipmaps for frame
	at net.minecraft.client.renderer.texture.TextureAtlasSprite.func_147963_d(TextureAtlasSprite.java:468)
	at com.rwtema.extrautils2.textures.SpriteLoaderProcessing.load(SpriteLoaderProcessing.java:60)
	at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:213)
	at matteroverdrive.client.render.RenderParticlesHandler.<init>(RenderParticlesHandler.java:68)
	at matteroverdrive.client.RenderHandler.init(RenderHandler.java:209)
	at matteroverdrive.proxy.ClientProxy.init(ClientProxy.java:130)
	at matteroverdrive.MatterOverdrive.init(MatterOverdrive.java:178)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:616)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:805)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:334)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ArrayIndexOutOfBoundsException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 851710816 bytes (812 MB) / 2070413312 bytes (1974 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2316 Optifine OptiFine_1.10.2_HD_U_D8 18 mods loaded, 18 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHI	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHI	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2316.jar) 
	UCHI	Forge{12.18.3.2316} [Minecraft Forge] (forge-1.10.2-12.18.3.2316.jar) 
	UCHI	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCHI	chisel{MC1.10.2-0.0.10.22} [Chisel] (Chisel-MC1.10.2-0.0.10.22.jar) 
	UCHI	galacticraftcore{4.0.0} [Galacticraft Core] (GalacticraftCore-1.10.2-4.0.0.107.jar) 
	UCHI	galacticraftplanets{4.0.0} [Galacticraft Planets] (Galacticraft-Planets-1.10.2-4.0.0.107.jar) 
	UCHI	extraplanets{0.4.6-Beta-Build} [Extra Planets] (ExtraPlanets-0.4.6-Beta-Build.jar) 
	UCHI	JEI{3.14.7.419} [Just Enough Items] (jei_1.10.2-3.14.7.419.jar) 
	UCHI	extrautils2{1.0} [Extra Utilities 2] (extrautils2-1.10.2-1.4.4.jar) 
	UCHI	forgelin{1.4.2} [Shadowfacts' Forgelin] (Forgelin-1.5.0.jar) 
	UCHI	journeymap{1.10.2-5.4.6} [JourneyMap] (journeymap-1.10.2-5.4.6.jar) 
	UCHI	justenoughbuttons{1.10.2-1.8.3} [Just Enough Buttons] (justenoughbuttons-1.10.2-1.8.3.jar) 
	UCHI	mantle{1.10.2-1.1.5.205} [Mantle] (Mantle-1.10.2-1.1.5.jar) 
	UCHI	shadowmc{3.6.1} [ShadowMC] (ShadowMC-1.10.2-3.6.1.jar) 
	UCHI	tesla{1.2.1.49} [TESLA] (Tesla-1.10.2-1.2.1.49.jar) 
	UCHE	mo{0.5.1} [Matter Overdrive] (MatterOverdrive-1.10.2-0.5.1.jar) 
	UCHI	tconstruct{1.10.2-2.6.5.10} [Tinkers' Construct] (TConstruct-1.10.2-2.6.5.jar) 
	Loaded coremods (and transformers): 
MicdoodlePlugin (MicdoodleCore-1.10.2-4.0.0.107.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
ForgelinPlugin (Forgelin-1.5.0.jar)
  
ChiselCorePlugin (Chisel-MC1.10.2-0.0.10.22.jar)
  team.chisel.common.asm.ChiselTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13421 Compatibility Profile Context 16.101.1611.1003' Renderer: 'AMD Radeon R5 Graphics'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	OptiFine Version: OptiFine_1.10.2_HD_U_D8
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.13421 Compatibility Profile Context 16.101.1611.1003
	OpenGlRenderer: AMD Radeon R5 Graphics
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4

**Comment by Muirrum** [comment]
Please for the love of god. Use [Pastebin](https://pastebin.com).

**Comment by Muirrum** [comment]
Closing due to lack of response and lack of description of issue.
