### ISSUE TITLE
Texture: wrcbe:remote_0 is already registered

### ISSUE THREAD

**Issue by YukiRainee** [simeonradivoev/MatterOverdrive#702]
`The following problems were captured during this phase
20:57:21	FML	Caught exception from Matter Overdrive (mo)
java.lang.IllegalStateException: Texture: wrcbe:remote_0 is already registered
	at codechicken.lib.texture.TextureUtils.getTextureSpecial(TextureUtils.java:133)
	at codechicken.wirelessredstone.client.texture.RemoteTexManager.registerIcons(RemoteTexManager.java:25)
	at codechicken.lib.texture.TextureUtils.textureLoad(TextureUtils.java:69)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_62_TextureUtils_textureLoad_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.client.ForgeHooksClient.onTextureStitchedPre(ForgeHooksClient.java:181)
	at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:105)
	at matteroverdrive.client.render.RenderParticlesHandler.<init>(RenderParticlesHandler.java:68)
	at matteroverdrive.client.RenderHandler.init(RenderHandler.java:209)
	at matteroverdrive.proxy.ClientProxy.init(ClientProxy.java:130)
	at matteroverdrive.MatterOverdrive.init(MatterOverdrive.java:178)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:616)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:805)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:334)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)`

Seems like something in your mod is trying to register and item thats the same from the wirelessredstonecbe mod I'll also be reporting this to the maintainer of that mod as well in case this isn't related to this mod but I figured just in case it might I would post it here too if you need more info let me know 
Basic info:
Minecraft version 1.10.2
Forge: 12.18.3.2316
Matter Overdrive Version: 0.5.1

**Comment by YukiRainee** [comment]
nvm found out that you already know about this... so im just gonna close this
