### ISSUE TITLE
0.4.0-RC1 seems to request client-only code on servers

### ISSUE THREAD

**Issue by netzgeist** [simeonradivoev/MatterOverdrive#85]
Dedicatedly updated MO from 0.3.5 to 0.4.0-RC1:

    Description: Exception in server tick loop

    cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraft/client/multiplayer/WorldClient
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:559)
	at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:88)
	at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:314)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
    Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/multiplayer/WorldClient
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2658)
	at java.lang.Class.getConstructor0(Class.java:2964)
	at java.lang.Class.newInstance(Class.java:403)
	at cpw.mods.fml.common.network.simpleimpl.SimpleNetworkWrapper.instantiate(SimpleNetworkWrapper.java:113)
	at cpw.mods.fml.common.network.simpleimpl.SimpleNetworkWrapper.registerMessage(SimpleNetworkWrapper.java:106)
	at matteroverdrive.network.PacketPipeline.registerPacket(PacketPipeline.java:70)
	at matteroverdrive.network.PacketPipeline.registerPackets(PacketPipeline.java:60)
	at matteroverdrive.MatterOverdrive.preInit(MatterOverdrive.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
	... 5 more
    Caused by: java.lang.ClassNotFoundException: net.minecraft.client.multiplayer.WorldClient
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 40 more
    Caused by: java.lang.RuntimeException: Attempted to load class bjf for invalid side SERVER
	at cpw.mods.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:50)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 42 more

Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 149 mods loaded, 149 mods active

Reverting back to 0.3.5 fixes the crash issue.

**Comment by TheVizzy** [comment]
That bug this version you need to install computercraft and waila and will be ok!

**Comment by TheVizzy** [comment]
PLZ don't repeat that bug)

**Comment by TheVizzy** [comment]
And don't fuck Simeon brain 😃

**Comment by netzgeist** [comment]
@TheVizzy other mods involved in the test:

http://pastebin.com/1QPcRwNW
(TLDR; Waila there, CC there)

Error occured, so having WAILA and CC be included does not prevent the issue from happening.

**Comment by b0bst3r** [comment]
https://github.com/simeonradivoev/MatterOverdrive/issues/80 if was fixed but no new build since that's why all these issues are being posted and re-posted.

Any chance of a build simeon, please?

**Comment by netzgeist** [comment]
#80 reads like a client crash on startup. #85 (mine) exclusively says the server crashes on startup, meaning i *can* run 0.4.0-RC1 clientsided.

**Comment by simeonradivoev** [comment]
Fixed in 9ee5f609152134b1537e591c1d0e85d5839a5541
